// @generated by scripts/gen-single-hop-assets.py; do not edit by hand.
// Source: https://1click.chaindefuser.com/v0/tokens

use crate::services::{
    asset_registry::ProviderId,
    single_hop_assets::{
        RouterAssetKind, VenueAssetEntry, VenueAssetMapSpec, VenueAssetPolicy, VenueChainAssetsSpec,
    },
};

const NEAR_INTENTS_BITCOIN_ASSETS: &[VenueAssetEntry] = &[VenueAssetEntry {
    router_asset: RouterAssetKind::Native,
    venue_asset: "nep141:btc.omft.near",
}];

const NEAR_INTENTS_EVM_1_ASSETS: &[VenueAssetEntry] = &[
    VenueAssetEntry {
        router_asset: RouterAssetKind::Native,
        venue_asset: "nep141:eth.omft.near",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x06ea695b91700071b161a434fed42d1dcbad9f00"),
        venue_asset: "nep141:eth-0x06ea695b91700071b161a434fed42d1dcbad9f00.omft.near",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x1f9840a85d5af5bf1d1762f925bdaddc4201f984"),
        venue_asset: "nep141:eth-0x1f9840a85d5af5bf1d1762f925bdaddc4201f984.omft.near",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x2260fac5e5542a773aa44fbcfedf7c193bc2c599"),
        venue_asset: "nep141:eth-0x2260fac5e5542a773aa44fbcfedf7c193bc2c599.omft.near",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x514910771af9ca656af840dff83e8264ecf986ca"),
        venue_asset: "nep141:eth-0x514910771af9ca656af840dff83e8264ecf986ca.omft.near",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x5afe3855358e112b5647b952709e6165e1c1eeee"),
        venue_asset: "nep141:eth-0x5afe3855358e112b5647b952709e6165e1c1eeee.omft.near",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x68749665ff8d2d112fa859aa293f07a622782f38"),
        venue_asset: "nep141:eth-0x68749665ff8d2d112fa859aa293f07a622782f38.omft.near",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x6982508145454ce325ddbe47a25d4ec3d2311933"),
        venue_asset: "nep141:eth-0x6982508145454ce325ddbe47a25d4ec3d2311933.omft.near",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x6b175474e89094c44da98b954eedeac495271d0f"),
        venue_asset: "nep141:eth-0x6b175474e89094c44da98b954eedeac495271d0f.omft.near",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9"),
        venue_asset: "nep141:eth-0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9.omft.near",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x8b1484d57abbe239bb280661377363b03c89caea"),
        venue_asset: "nep141:eth-0x8b1484d57abbe239bb280661377363b03c89caea.omft.near",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x8d0d000ee44948fc98c9b98a4fa4921476f08b0d"),
        venue_asset: "nep141:eth-0x8d0d000ee44948fc98c9b98a4fa4921476f08b0d.omft.near",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x95ad61b0a150d79219dcf64e1e6cc01f0b64c4ce"),
        venue_asset: "nep141:eth-0x95ad61b0a150d79219dcf64e1e6cc01f0b64c4ce.omft.near",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"),
        venue_asset: "nep141:eth-0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48.omft.near",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xa35923162c49cf95e6bf26623385eb431ad920d3"),
        venue_asset: "nep141:eth-0xa35923162c49cf95e6bf26623385eb431ad920d3.omft.near",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xaaaaaa20d9e0e2461697782ef11675f668207961"),
        venue_asset: "nep141:eth-0xaaaaaa20d9e0e2461697782ef11675f668207961.omft.near",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xaaee1a9723aadb7afa2810263653a34ba2c21c7a"),
        venue_asset: "nep141:eth-0xaaee1a9723aadb7afa2810263653a34ba2c21c7a.omft.near",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xb4b9dc1c77bdbb135ea907fd5a08094d98883a35"),
        venue_asset: "nep141:eth-0xb4b9dc1c77bdbb135ea907fd5a08094d98883a35.omft.near",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xbeef01735c132ada46aa9aa4c54623caa92a64cb"),
        venue_asset: "nep141:eth-0xbeef01735c132ada46aa9aa4c54623caa92a64cb.omft.near",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"),
        venue_asset: "nep141:eth-0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2.omft.near",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xcbb7c0000ab88b473b1f5afd9ef808440eed33bf"),
        venue_asset: "nep141:eth-0xcbb7c0000ab88b473b1f5afd9ef808440eed33bf.omft.near",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xd9c2d319cd7e6177336b0a9c93c21cb48d84fb54"),
        venue_asset: "nep141:eth-0xd9c2d319cd7e6177336b0a9c93c21cb48d84fb54.omft.near",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xdac17f958d2ee523a2206206994597c13d831ec7"),
        venue_asset: "nep141:eth-0xdac17f958d2ee523a2206206994597c13d831ec7.omft.near",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xdef1b2d939edc0e4d35806c59b3166f790175afe"),
        venue_asset: "nep141:eth-0xdef1b2d939edc0e4d35806c59b3166f790175afe.omft.near",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xdefa4e8a7bcba345f687a2f1456f5edd9ce97202"),
        venue_asset: "nep141:eth-0xdefa4e8a7bcba345f687a2f1456f5edd9ce97202.omft.near",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xe0f63a424a4439cbe457d80e4f4b51ad25b2c56c"),
        venue_asset: "nep141:eth-0xe0f63a424a4439cbe457d80e4f4b51ad25b2c56c.omft.near",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xfa2b947eec368f42195f24f36d2af29f7c24cec2"),
        venue_asset: "nep141:eth-0xfa2b947eec368f42195f24f36d2af29f7c24cec2.omft.near",
    },
];

const NEAR_INTENTS_EVM_42161_ASSETS: &[VenueAssetEntry] = &[
    VenueAssetEntry {
        router_asset: RouterAssetKind::Native,
        venue_asset: "nep141:arb.omft.near",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x82af49447d8a07e3bd95bd0d56f35241523fbab1"),
        venue_asset: "nep141:arb-0x82af49447d8a07e3bd95bd0d56f35241523fbab1.omft.near",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x912ce59144191c1204e64559fe8253a0e49e6548"),
        venue_asset: "nep141:arb-0x912ce59144191c1204e64559fe8253a0e49e6548.omft.near",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xaf88d065e77c8cc2239327c5edb3a432268e5831"),
        venue_asset: "nep141:arb-0xaf88d065e77c8cc2239327c5edb3a432268e5831.omft.near",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xca7dec8550f43a5e46e3dfb95801f64280e75b27"),
        venue_asset: "nep141:arb-0xca7dec8550f43a5e46e3dfb95801f64280e75b27.omft.near",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xfc5a1a6eb076a2c7ad06ed22c90d7e710e35ad0a"),
        venue_asset: "nep141:arb-0xfc5a1a6eb076a2c7ad06ed22c90d7e710e35ad0a.omft.near",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xfd086bc7cd5c481dcc9c85ebe478a1c0b69fcbb9"),
        venue_asset: "nep141:arb-0xfd086bc7cd5c481dcc9c85ebe478a1c0b69fcbb9.omft.near",
    },
];

const NEAR_INTENTS_EVM_8453_ASSETS: &[VenueAssetEntry] = &[
    VenueAssetEntry {
        router_asset: RouterAssetKind::Native,
        venue_asset: "nep141:base.omft.near",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x0382e3fee4a420bd446367d468a6f00225853420"),
        venue_asset: "1cs_v1:base:erc20:0x0382e3fee4a420bd446367d468a6f00225853420",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x1c4a802fd6b591bb71daa01d8335e43719048b24"),
        venue_asset: "nep141:base-0x1c4a802fd6b591bb71daa01d8335e43719048b24.omft.near",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x227d920e20ebac8a40e7d6431b7d724bb64d7245"),
        venue_asset: "nep141:base-0x227d920e20ebac8a40e7d6431b7d724bb64d7245.omft.near",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x4200000000000000000000000000000000000006"),
        venue_asset: "nep141:base-0x4200000000000000000000000000000000000006.omft.near",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x532f27101965dd16442e59d40670faf5ebb142e4"),
        venue_asset: "nep141:base-0x532f27101965dd16442e59d40670faf5ebb142e4.omft.near",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x7bfa7c4f149e7415b73bdedfe609237e29cbf34a"),
        venue_asset: "nep141:base-0x7bfa7c4f149e7415b73bdedfe609237e29cbf34a.omft.near",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x833589fcd6edb6e08f4c7c32d4f71b54bda02913"),
        venue_asset: "nep141:base-0x833589fcd6edb6e08f4c7c32d4f71b54bda02913.omft.near",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x98d0baa52b2d063e780de12f615f963fe8537553"),
        venue_asset: "nep141:base-0x98d0baa52b2d063e780de12f615f963fe8537553.omft.near",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xa5c67d8d37b88c2d88647814da5578128e2c93b2"),
        venue_asset: "nep141:base-0xa5c67d8d37b88c2d88647814da5578128e2c93b2.omft.near",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xacfe6019ed1a7dc6f7b508c02d1b04ec88cc21bf"),
        venue_asset: "nep141:base-0xacfe6019ed1a7dc6f7b508c02d1b04ec88cc21bf.omft.near",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xc1256ae5ff1cf2719d4937adb3bbccab2e00a2ca"),
        venue_asset: "nep141:base-0xc1256ae5ff1cf2719d4937adb3bbccab2e00a2ca.omft.near",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xc2bc2a4cd04358281c7cf36a057fc15e5552b18b"),
        venue_asset: "nep141:base-0xc2bc2a4cd04358281c7cf36a057fc15e5552b18b.omdep.near",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xcbb7c0000ab88b473b1f5afd9ef808440eed33bf"),
        venue_asset: "nep141:base-0xcbb7c0000ab88b473b1f5afd9ef808440eed33bf.omft.near",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xe62bfbe57763ec24c0f130426f34dbce11fc5b06"),
        venue_asset: "nep141:base-0xe62bfbe57763ec24c0f130426f34dbce11fc5b06.omft.near",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xee8f4ec5672f09119b96ab6fb59c27e1b7e44b61"),
        venue_asset: "nep141:base-0xee8f4ec5672f09119b96ab6fb59c27e1b7e44b61.omft.near",
    },
];

const NEAR_INTENTS_CHAINS: &[VenueChainAssetsSpec] = &[
    VenueChainAssetsSpec {
        router_chain: "bitcoin",
        venue_chain: "btc",
        asset_policy: VenueAssetPolicy::ListedOnly,
        assets: NEAR_INTENTS_BITCOIN_ASSETS,
    },
    VenueChainAssetsSpec {
        router_chain: "evm:1",
        venue_chain: "eth",
        asset_policy: VenueAssetPolicy::ListedOnly,
        assets: NEAR_INTENTS_EVM_1_ASSETS,
    },
    VenueChainAssetsSpec {
        router_chain: "evm:42161",
        venue_chain: "arb",
        asset_policy: VenueAssetPolicy::ListedOnly,
        assets: NEAR_INTENTS_EVM_42161_ASSETS,
    },
    VenueChainAssetsSpec {
        router_chain: "evm:8453",
        venue_chain: "base",
        asset_policy: VenueAssetPolicy::ListedOnly,
        assets: NEAR_INTENTS_EVM_8453_ASSETS,
    },
];

pub const NEAR_INTENTS_ASSET_MAP_SPEC: VenueAssetMapSpec = VenueAssetMapSpec {
    provider: ProviderId::NearIntents,
    chains: NEAR_INTENTS_CHAINS,
};
