// @generated by scripts/gen-single-hop-assets.py; do not edit by hand.
// Source: https://sia.mayan.finance/v10/init

use crate::services::{
    asset_registry::ProviderId,
    single_hop_assets::{
        ContractEncoding, ContractPassthrough, ContractStandard, RouterAssetKind, VenueAssetEntry,
        VenueAssetMapSpec, VenueAssetPolicy, VenueChainAssetsSpec,
    },
};

const MAYAN_EVM_CONTRACT_PASSTHROUGH: ContractPassthrough = ContractPassthrough {
    standard: ContractStandard::Erc20,
    encoding: ContractEncoding::LowercaseHex,
};

const MAYAN_EVM_1_ASSETS: &[VenueAssetEntry] = &[VenueAssetEntry {
    router_asset: RouterAssetKind::Native,
    venue_asset: "0x0000000000000000000000000000000000000000",
}];

const MAYAN_EVM_42161_ASSETS: &[VenueAssetEntry] = &[VenueAssetEntry {
    router_asset: RouterAssetKind::Native,
    venue_asset: "0x0000000000000000000000000000000000000000",
}];

const MAYAN_EVM_8453_ASSETS: &[VenueAssetEntry] = &[VenueAssetEntry {
    router_asset: RouterAssetKind::Native,
    venue_asset: "0x0000000000000000000000000000000000000000",
}];

const MAYAN_CHAINS: &[VenueChainAssetsSpec] = &[
    VenueChainAssetsSpec {
        router_chain: "evm:1",
        venue_chain: "ethereum",
        asset_policy: VenueAssetPolicy::ListedPlusOpenContracts(MAYAN_EVM_CONTRACT_PASSTHROUGH),
        assets: MAYAN_EVM_1_ASSETS,
    },
    VenueChainAssetsSpec {
        router_chain: "evm:42161",
        venue_chain: "arbitrum",
        asset_policy: VenueAssetPolicy::ListedPlusOpenContracts(MAYAN_EVM_CONTRACT_PASSTHROUGH),
        assets: MAYAN_EVM_42161_ASSETS,
    },
    VenueChainAssetsSpec {
        router_chain: "evm:8453",
        venue_chain: "base",
        asset_policy: VenueAssetPolicy::ListedPlusOpenContracts(MAYAN_EVM_CONTRACT_PASSTHROUGH),
        assets: MAYAN_EVM_8453_ASSETS,
    },
];

pub const MAYAN_ASSET_MAP_SPEC: VenueAssetMapSpec = VenueAssetMapSpec {
    provider: ProviderId::Mayan,
    chains: MAYAN_CHAINS,
};
