-- Router primary schema baseline.
-- Generated by squashing the prior migration chain into the final public schema.

CREATE FUNCTION public.update_updated_at_column() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;


CREATE TABLE public.custody_vaults (
    id uuid NOT NULL,
    order_id uuid,
    role text NOT NULL,
    visibility text NOT NULL,
    chain_id text NOT NULL,
    asset_id text,
    address text NOT NULL,
    control_type text NOT NULL,
    derivation_salt bytea,
    signer_ref text,
    status text NOT NULL,
    metadata_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT custody_vaults_address_not_empty CHECK ((address <> ''::text)),
    CONSTRAINT custody_vaults_asset_id_not_empty CHECK (((asset_id IS NULL) OR (asset_id <> ''::text))),
    CONSTRAINT custody_vaults_chain_id_not_empty CHECK ((chain_id <> ''::text)),
    CONSTRAINT custody_vaults_control_type_check CHECK ((control_type = ANY (ARRAY['router_derived_key'::text, 'paymaster_wallet'::text, 'hyperliquid_master_signer'::text, 'external_user'::text, 'watch_only'::text]))),
    CONSTRAINT custody_vaults_derivation_salt_len CHECK (((derivation_salt IS NULL) OR (octet_length(derivation_salt) = 32))),
    CONSTRAINT custody_vaults_metadata_object CHECK ((jsonb_typeof(metadata_json) = 'object'::text)),
    CONSTRAINT custody_vaults_role_check CHECK ((role = ANY (ARRAY['source_deposit'::text, 'destination_execution'::text, 'hyperliquid_spot'::text]))),
    CONSTRAINT custody_vaults_signer_ref_not_empty CHECK (((signer_ref IS NULL) OR (signer_ref <> ''::text))),
    CONSTRAINT custody_vaults_status_check CHECK ((status = ANY (ARRAY['planned'::text, 'active'::text, 'released'::text, 'failed'::text]))),
    CONSTRAINT custody_vaults_visibility_check CHECK ((visibility = ANY (ARRAY['user_facing'::text, 'internal'::text, 'watch_only'::text])))
);



CREATE TABLE public.deposit_vault_funding_hints (
    id uuid NOT NULL,
    vault_id uuid NOT NULL,
    source text NOT NULL,
    hint_kind text NOT NULL,
    evidence_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    status text NOT NULL,
    idempotency_key text,
    error_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    claimed_at timestamp with time zone,
    processed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT deposit_vault_funding_hints_error_object CHECK ((jsonb_typeof(error_json) = 'object'::text)),
    CONSTRAINT deposit_vault_funding_hints_evidence_object CHECK ((jsonb_typeof(evidence_json) = 'object'::text)),
    CONSTRAINT deposit_vault_funding_hints_idempotency_key_not_empty CHECK (((idempotency_key IS NULL) OR (idempotency_key <> ''::text))),
    CONSTRAINT deposit_vault_funding_hints_kind_check CHECK ((hint_kind = 'possible_progress'::text)),
    CONSTRAINT deposit_vault_funding_hints_source_not_empty CHECK ((source <> ''::text)),
    CONSTRAINT deposit_vault_funding_hints_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'processing'::text, 'processed'::text, 'ignored'::text, 'failed'::text])))
);



CREATE TABLE public.deposit_vaults (
    id uuid NOT NULL,
    action jsonb NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    recovery_address character varying(255) NOT NULL,
    cancellation_commitment bytea NOT NULL,
    cancel_after timestamp with time zone NOT NULL,
    status text NOT NULL,
    refund_requested_at timestamp with time zone,
    refunded_at timestamp with time zone,
    refund_tx_hash text,
    last_refund_error text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    refund_attempt_count integer DEFAULT 0 NOT NULL,
    last_refund_attempt_at timestamp with time zone,
    refund_next_attempt_at timestamp with time zone,
    refund_claimed_by text,
    refund_claimed_until timestamp with time zone,
    CONSTRAINT deposit_vault_cancellation_commitment_len CHECK ((octet_length(cancellation_commitment) = 32)),
    CONSTRAINT deposit_vault_status_check CHECK ((status = ANY (ARRAY['pending_funding'::text, 'funded'::text, 'executing'::text, 'completed'::text, 'refund_required'::text, 'refunding'::text, 'refunded'::text, 'refund_manual_intervention_required'::text])))
);



CREATE TABLE public.market_order_actions (
    order_id uuid NOT NULL,
    order_kind text NOT NULL,
    amount_in text,
    min_amount_out text,
    amount_out text,
    max_amount_in text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    slippage_bps bigint NOT NULL,
    CONSTRAINT market_order_actions_amount_in_digits CHECK (((amount_in IS NULL) OR (amount_in ~ '^[0-9]+$'::text))),
    CONSTRAINT market_order_actions_amount_out_digits CHECK (((amount_out IS NULL) OR (amount_out ~ '^[0-9]+$'::text))),
    CONSTRAINT market_order_actions_max_amount_in_digits CHECK (((max_amount_in IS NULL) OR (max_amount_in ~ '^[0-9]+$'::text))),
    CONSTRAINT market_order_actions_min_amount_out_digits CHECK (((min_amount_out IS NULL) OR (min_amount_out ~ '^[0-9]+$'::text))),
    CONSTRAINT market_order_actions_order_kind_check CHECK ((order_kind = ANY (ARRAY['exact_in'::text, 'exact_out'::text]))),
    CONSTRAINT market_order_actions_shape_check CHECK ((((order_kind = 'exact_in'::text) AND (amount_in IS NOT NULL) AND (min_amount_out IS NOT NULL) AND (amount_out IS NULL) AND (max_amount_in IS NULL)) OR ((order_kind = 'exact_out'::text) AND (amount_in IS NULL) AND (min_amount_out IS NULL) AND (amount_out IS NOT NULL) AND (max_amount_in IS NOT NULL)))),
    CONSTRAINT market_order_actions_slippage_bps_check CHECK (((slippage_bps >= 0) AND (slippage_bps <= 10000)))
);



CREATE TABLE public.market_order_quotes (
    id uuid NOT NULL,
    order_id uuid,
    provider_id text NOT NULL,
    order_kind text NOT NULL,
    amount_in text NOT NULL,
    amount_out text NOT NULL,
    min_amount_out text,
    max_amount_in text,
    provider_quote jsonb DEFAULT '{}'::jsonb NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    source_chain_id text NOT NULL,
    source_asset_id text NOT NULL,
    destination_chain_id text NOT NULL,
    destination_asset_id text NOT NULL,
    recipient_address text NOT NULL,
    slippage_bps bigint NOT NULL,
    CONSTRAINT market_order_quotes_amount_in_digits CHECK ((amount_in ~ '^[0-9]+$'::text)),
    CONSTRAINT market_order_quotes_amount_out_digits CHECK ((amount_out ~ '^[0-9]+$'::text)),
    CONSTRAINT market_order_quotes_destination_asset_not_empty CHECK ((destination_asset_id <> ''::text)),
    CONSTRAINT market_order_quotes_destination_chain_not_empty CHECK ((destination_chain_id <> ''::text)),
    CONSTRAINT market_order_quotes_max_amount_in_digits CHECK (((max_amount_in IS NULL) OR (max_amount_in ~ '^[0-9]+$'::text))),
    CONSTRAINT market_order_quotes_min_amount_out_digits CHECK (((min_amount_out IS NULL) OR (min_amount_out ~ '^[0-9]+$'::text))),
    CONSTRAINT market_order_quotes_order_kind_check CHECK ((order_kind = ANY (ARRAY['exact_in'::text, 'exact_out'::text]))),
    CONSTRAINT market_order_quotes_provider_id_not_empty CHECK ((provider_id <> ''::text)),
    CONSTRAINT market_order_quotes_recipient_address_not_empty CHECK ((recipient_address <> ''::text)),
    CONSTRAINT market_order_quotes_slippage_bps_check CHECK (((slippage_bps >= 0) AND (slippage_bps <= 10000))),
    CONSTRAINT market_order_quotes_source_asset_not_empty CHECK ((source_asset_id <> ''::text)),
    CONSTRAINT market_order_quotes_source_chain_not_empty CHECK ((source_chain_id <> ''::text))
);



CREATE TABLE public.order_execution_attempts (
    id uuid NOT NULL,
    order_id uuid NOT NULL,
    attempt_index integer NOT NULL,
    attempt_kind text NOT NULL,
    status text NOT NULL,
    trigger_step_id uuid,
    trigger_provider_operation_id uuid,
    failure_reason_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    input_custody_snapshot_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT order_execution_attempts_attempt_index_positive CHECK ((attempt_index > 0)),
    CONSTRAINT order_execution_attempts_attempt_kind_check CHECK ((attempt_kind = ANY (ARRAY['primary_execution'::text, 'retry_execution'::text, 'refund_recovery'::text]))),
    CONSTRAINT order_execution_attempts_failure_reason_object CHECK ((jsonb_typeof(failure_reason_json) = 'object'::text)),
    CONSTRAINT order_execution_attempts_input_custody_snapshot_object CHECK ((jsonb_typeof(input_custody_snapshot_json) = 'object'::text)),
    CONSTRAINT order_execution_attempts_status_check CHECK ((status = ANY (ARRAY['planning'::text, 'active'::text, 'completed'::text, 'failed'::text, 'refund_required'::text, 'manual_intervention_required'::text])))
);



CREATE TABLE public.order_execution_steps (
    id uuid NOT NULL,
    order_id uuid NOT NULL,
    transition_decl_id text,
    step_index integer NOT NULL,
    step_type text NOT NULL,
    provider text NOT NULL,
    status text NOT NULL,
    input_chain_id text,
    input_asset_id text,
    output_chain_id text,
    output_asset_id text,
    amount_in text,
    min_amount_out text,
    tx_hash text,
    provider_ref text,
    idempotency_key text,
    attempt_count integer DEFAULT 0 NOT NULL,
    next_attempt_at timestamp with time zone,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    details_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    request_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    response_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    error_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    execution_attempt_id uuid,
    CONSTRAINT order_execution_steps_amount_in_digits CHECK (((amount_in IS NULL) OR (amount_in ~ '^[0-9]+$'::text))),
    CONSTRAINT order_execution_steps_attempt_count_nonnegative CHECK ((attempt_count >= 0)),
    CONSTRAINT order_execution_steps_details_object CHECK ((jsonb_typeof(details_json) = 'object'::text)),
    CONSTRAINT order_execution_steps_error_object CHECK ((jsonb_typeof(error_json) = 'object'::text)),
    CONSTRAINT order_execution_steps_idempotency_key_not_empty CHECK (((idempotency_key IS NULL) OR (idempotency_key <> ''::text))),
    CONSTRAINT order_execution_steps_input_asset_pair CHECK ((((input_chain_id IS NULL) AND (input_asset_id IS NULL)) OR ((input_chain_id IS NOT NULL) AND (input_asset_id IS NOT NULL)))),
    CONSTRAINT order_execution_steps_lifecycle_timestamps CHECK (((completed_at IS NULL) OR (started_at IS NULL) OR (completed_at >= started_at))),
    CONSTRAINT order_execution_steps_min_amount_out_digits CHECK (((min_amount_out IS NULL) OR (min_amount_out ~ '^[0-9]+$'::text))),
    CONSTRAINT order_execution_steps_output_asset_pair CHECK ((((output_chain_id IS NULL) AND (output_asset_id IS NULL)) OR ((output_chain_id IS NOT NULL) AND (output_asset_id IS NOT NULL)))),
    CONSTRAINT order_execution_steps_provider_not_empty CHECK ((provider <> ''::text)),
    CONSTRAINT order_execution_steps_provider_ref_not_empty CHECK (((provider_ref IS NULL) OR (provider_ref <> ''::text))),
    CONSTRAINT order_execution_steps_request_object CHECK ((jsonb_typeof(request_json) = 'object'::text)),
    CONSTRAINT order_execution_steps_response_object CHECK ((jsonb_typeof(response_json) = 'object'::text)),
    CONSTRAINT order_execution_steps_status_check CHECK ((status = ANY (ARRAY['planned'::text, 'waiting'::text, 'ready'::text, 'running'::text, 'completed'::text, 'failed'::text, 'skipped'::text, 'cancelled'::text]))),
    CONSTRAINT order_execution_steps_step_index_nonnegative CHECK ((step_index >= 0)),
    CONSTRAINT order_execution_steps_step_type_check CHECK ((step_type = ANY (ARRAY['wait_for_deposit'::text, 'across_bridge'::text, 'cctp_burn'::text, 'cctp_receive'::text, 'unit_deposit'::text, 'unit_withdrawal'::text, 'hyperliquid_trade'::text, 'hyperliquid_bridge_deposit'::text, 'universal_router_swap'::text, 'refund'::text]))),
    CONSTRAINT order_execution_steps_transition_decl_id_not_empty CHECK (((transition_decl_id IS NULL) OR (transition_decl_id <> ''::text))),
    CONSTRAINT order_execution_steps_tx_hash_not_empty CHECK (((tx_hash IS NULL) OR (tx_hash <> ''::text)))
);



CREATE TABLE public.order_provider_addresses (
    id uuid NOT NULL,
    order_id uuid NOT NULL,
    execution_step_id uuid,
    provider_operation_id uuid,
    provider text NOT NULL,
    role text NOT NULL,
    chain_id text NOT NULL,
    asset_id text,
    address text NOT NULL,
    memo text,
    expires_at timestamp with time zone,
    metadata_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT order_provider_addresses_address_not_empty CHECK ((address <> ''::text)),
    CONSTRAINT order_provider_addresses_asset_id_not_empty CHECK (((asset_id IS NULL) OR (asset_id <> ''::text))),
    CONSTRAINT order_provider_addresses_chain_id_not_empty CHECK ((chain_id <> ''::text)),
    CONSTRAINT order_provider_addresses_memo_not_empty CHECK (((memo IS NULL) OR (memo <> ''::text))),
    CONSTRAINT order_provider_addresses_metadata_object CHECK ((jsonb_typeof(metadata_json) = 'object'::text)),
    CONSTRAINT order_provider_addresses_provider_not_empty CHECK ((provider <> ''::text)),
    CONSTRAINT order_provider_addresses_role_check CHECK ((role = ANY (ARRAY['across_recipient'::text, 'across_refund'::text, 'unit_deposit'::text, 'unit_revert'::text, 'hyperliquid_destination'::text])))
);



CREATE TABLE public.order_provider_operation_hints (
    id uuid NOT NULL,
    provider_operation_id uuid NOT NULL,
    source text NOT NULL,
    hint_kind text NOT NULL,
    evidence_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    status text NOT NULL,
    idempotency_key text,
    error_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    claimed_at timestamp with time zone,
    processed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT order_provider_operation_hints_error_object CHECK ((jsonb_typeof(error_json) = 'object'::text)),
    CONSTRAINT order_provider_operation_hints_evidence_object CHECK ((jsonb_typeof(evidence_json) = 'object'::text)),
    CONSTRAINT order_provider_operation_hints_idempotency_key_not_empty CHECK (((idempotency_key IS NULL) OR (idempotency_key <> ''::text))),
    CONSTRAINT order_provider_operation_hints_kind_check CHECK ((hint_kind = 'possible_progress'::text)),
    CONSTRAINT order_provider_operation_hints_source_not_empty CHECK ((source <> ''::text)),
    CONSTRAINT order_provider_operation_hints_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'processing'::text, 'processed'::text, 'ignored'::text, 'failed'::text])))
);



CREATE TABLE public.order_provider_operations (
    id uuid NOT NULL,
    order_id uuid NOT NULL,
    execution_step_id uuid,
    provider text NOT NULL,
    operation_type text NOT NULL,
    provider_ref text,
    status text NOT NULL,
    request_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    response_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    observed_state_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    execution_attempt_id uuid,
    CONSTRAINT order_provider_operations_observed_state_object CHECK ((jsonb_typeof(observed_state_json) = 'object'::text)),
    CONSTRAINT order_provider_operations_provider_not_empty CHECK ((provider <> ''::text)),
    CONSTRAINT order_provider_operations_provider_ref_not_empty CHECK (((provider_ref IS NULL) OR (provider_ref <> ''::text))),
    CONSTRAINT order_provider_operations_request_object CHECK ((jsonb_typeof(request_json) = 'object'::text)),
    CONSTRAINT order_provider_operations_response_object CHECK ((jsonb_typeof(response_json) = 'object'::text)),
    CONSTRAINT order_provider_operations_status_check CHECK ((status = ANY (ARRAY['planned'::text, 'submitted'::text, 'waiting_external'::text, 'completed'::text, 'failed'::text, 'expired'::text]))),
    CONSTRAINT order_provider_operations_type_check CHECK ((operation_type = ANY (ARRAY['across_bridge'::text, 'cctp_bridge'::text, 'unit_deposit'::text, 'unit_withdrawal'::text, 'hyperliquid_trade'::text, 'hyperliquid_bridge_deposit'::text, 'universal_router_swap'::text])))
);



CREATE TABLE public.paymaster_gas_ledger (
    id uuid NOT NULL,
    order_id uuid NOT NULL,
    execution_attempt_id uuid,
    execution_step_id uuid,
    debt_id text NOT NULL,
    spend_chain_id text NOT NULL,
    estimated_native_gas_wei text NOT NULL,
    estimated_usd_micro text NOT NULL,
    settlement_chain_id text NOT NULL,
    settlement_asset_id text NOT NULL,
    settlement_amount text NOT NULL,
    settlement_tx_hash text,
    actual_native_gas_wei text,
    actual_usd_micro text,
    status text NOT NULL,
    metadata_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT paymaster_gas_ledger_actual_native_digits CHECK (((actual_native_gas_wei IS NULL) OR (actual_native_gas_wei ~ '^[0-9]+$'::text))),
    CONSTRAINT paymaster_gas_ledger_actual_usd_digits CHECK (((actual_usd_micro IS NULL) OR (actual_usd_micro ~ '^[0-9]+$'::text))),
    CONSTRAINT paymaster_gas_ledger_debt_id_not_empty CHECK ((debt_id <> ''::text)),
    CONSTRAINT paymaster_gas_ledger_estimated_native_digits CHECK ((estimated_native_gas_wei ~ '^[0-9]+$'::text)),
    CONSTRAINT paymaster_gas_ledger_estimated_usd_digits CHECK ((estimated_usd_micro ~ '^[0-9]+$'::text)),
    CONSTRAINT paymaster_gas_ledger_metadata_object CHECK ((jsonb_typeof(metadata_json) = 'object'::text)),
    CONSTRAINT paymaster_gas_ledger_settlement_amount_digits CHECK ((settlement_amount ~ '^[0-9]+$'::text)),
    CONSTRAINT paymaster_gas_ledger_settlement_asset_not_empty CHECK ((settlement_asset_id <> ''::text)),
    CONSTRAINT paymaster_gas_ledger_settlement_chain_not_empty CHECK ((settlement_chain_id <> ''::text)),
    CONSTRAINT paymaster_gas_ledger_settlement_tx_hash_not_empty CHECK (((settlement_tx_hash IS NULL) OR (settlement_tx_hash <> ''::text))),
    CONSTRAINT paymaster_gas_ledger_spend_chain_not_empty CHECK ((spend_chain_id <> ''::text)),
    CONSTRAINT paymaster_gas_ledger_status_check CHECK ((status = ANY (ARRAY['quoted'::text, 'retained'::text, 'actualized'::text, 'rebate_due'::text, 'shortfall_due'::text, 'void'::text])))
);



CREATE TABLE public.provider_policies (
    provider text NOT NULL,
    quote_state text NOT NULL,
    execution_state text NOT NULL,
    reason text DEFAULT ''::text NOT NULL,
    updated_by text DEFAULT 'unknown'::text NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT provider_policies_execution_state_check CHECK ((execution_state = ANY (ARRAY['enabled'::text, 'drain'::text, 'disabled'::text]))),
    CONSTRAINT provider_policies_quote_state_check CHECK ((quote_state = ANY (ARRAY['enabled'::text, 'disabled'::text])))
);



CREATE TABLE public.router_orders (
    id uuid NOT NULL,
    order_type text NOT NULL,
    status text NOT NULL,
    funding_vault_id uuid,
    source_chain_id text NOT NULL,
    source_asset_id text NOT NULL,
    destination_chain_id text NOT NULL,
    destination_asset_id text NOT NULL,
    recipient_address text NOT NULL,
    refund_address text NOT NULL,
    action_timeout_at timestamp with time zone NOT NULL,
    idempotency_key text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT router_orders_destination_asset_not_empty CHECK ((destination_asset_id <> ''::text)),
    CONSTRAINT router_orders_destination_chain_not_empty CHECK ((destination_chain_id <> ''::text)),
    CONSTRAINT router_orders_idempotency_key_not_empty CHECK (((idempotency_key IS NULL) OR (idempotency_key <> ''::text))),
    CONSTRAINT router_orders_order_type_check CHECK ((order_type = 'market_order'::text)),
    CONSTRAINT router_orders_recipient_address_not_empty CHECK ((recipient_address <> ''::text)),
    CONSTRAINT router_orders_refund_address_not_empty CHECK ((refund_address <> ''::text)),
    CONSTRAINT router_orders_source_asset_not_empty CHECK ((source_asset_id <> ''::text)),
    CONSTRAINT router_orders_source_chain_not_empty CHECK ((source_chain_id <> ''::text)),
    CONSTRAINT router_orders_status_check CHECK ((status = ANY (ARRAY['quoted'::text, 'pending_funding'::text, 'funded'::text, 'executing'::text, 'completed'::text, 'refund_required'::text, 'refunding'::text, 'refunded'::text, 'refund_manual_intervention_required'::text, 'failed'::text, 'expired'::text])))
);



CREATE TABLE public.router_route_cost_snapshots (
    transition_id text NOT NULL,
    amount_bucket text NOT NULL,
    provider text NOT NULL,
    edge_kind text NOT NULL,
    source_chain text NOT NULL,
    source_asset text NOT NULL,
    destination_chain text NOT NULL,
    destination_asset text NOT NULL,
    estimated_fee_bps bigint NOT NULL,
    estimated_gas_usd_micros bigint NOT NULL,
    estimated_latency_ms bigint NOT NULL,
    sample_amount_usd_micros bigint NOT NULL,
    quote_source text NOT NULL,
    refreshed_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    CONSTRAINT router_route_cost_snapshots_estimated_fee_bps_check CHECK ((estimated_fee_bps >= 0)),
    CONSTRAINT router_route_cost_snapshots_estimated_gas_usd_micros_check CHECK ((estimated_gas_usd_micros >= 0)),
    CONSTRAINT router_route_cost_snapshots_estimated_latency_ms_check CHECK ((estimated_latency_ms >= 0)),
    CONSTRAINT router_route_cost_snapshots_sample_amount_usd_micros_check CHECK ((sample_amount_usd_micros > 0))
);



CREATE TABLE public.router_worker_leases (
    lease_name text NOT NULL,
    owner_id text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    fencing_token bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);



ALTER TABLE ONLY public.custody_vaults
    ADD CONSTRAINT custody_vaults_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.deposit_vault_funding_hints
    ADD CONSTRAINT deposit_vault_funding_hints_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.deposit_vaults
    ADD CONSTRAINT deposit_vaults_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.market_order_actions
    ADD CONSTRAINT market_order_actions_pkey PRIMARY KEY (order_id);



ALTER TABLE ONLY public.market_order_quotes
    ADD CONSTRAINT market_order_quotes_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.order_execution_attempts
    ADD CONSTRAINT order_execution_attempts_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.order_execution_steps
    ADD CONSTRAINT order_execution_steps_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.order_provider_addresses
    ADD CONSTRAINT order_provider_addresses_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.order_provider_operation_hints
    ADD CONSTRAINT order_provider_operation_hints_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.order_provider_operations
    ADD CONSTRAINT order_provider_operations_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.paymaster_gas_ledger
    ADD CONSTRAINT paymaster_gas_ledger_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.provider_policies
    ADD CONSTRAINT provider_policies_pkey PRIMARY KEY (provider);



ALTER TABLE ONLY public.router_orders
    ADD CONSTRAINT router_orders_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.router_route_cost_snapshots
    ADD CONSTRAINT router_route_cost_snapshots_pkey PRIMARY KEY (transition_id, amount_bucket);



ALTER TABLE ONLY public.router_worker_leases
    ADD CONSTRAINT router_worker_leases_pkey PRIMARY KEY (lease_name);



CREATE UNIQUE INDEX idx_custody_vaults_chain_address ON public.custody_vaults USING btree (chain_id, address);



CREATE INDEX idx_custody_vaults_order_id ON public.custody_vaults USING btree (order_id) WHERE (order_id IS NOT NULL);



CREATE INDEX idx_custody_vaults_order_role ON public.custody_vaults USING btree (order_id, role) WHERE (order_id IS NOT NULL);



CREATE UNIQUE INDEX idx_custody_vaults_order_role_chain_asset ON public.custody_vaults USING btree (order_id, role, chain_id, COALESCE(asset_id, ''::text)) WHERE (order_id IS NOT NULL);



CREATE INDEX idx_custody_vaults_role ON public.custody_vaults USING btree (role);



CREATE UNIQUE INDEX idx_deposit_vault_funding_hints_idempotency_key ON public.deposit_vault_funding_hints USING btree (source, idempotency_key) WHERE (idempotency_key IS NOT NULL);



CREATE INDEX idx_deposit_vault_funding_hints_pending ON public.deposit_vault_funding_hints USING btree (status, created_at) WHERE (status = ANY (ARRAY['pending'::text, 'processing'::text]));



CREATE INDEX idx_deposit_vault_funding_hints_vault_id ON public.deposit_vault_funding_hints USING btree (vault_id, created_at);



CREATE INDEX idx_deposit_vaults_created_at ON public.deposit_vaults USING btree (created_at DESC);



CREATE INDEX idx_deposit_vaults_refunding_claimable ON public.deposit_vaults USING btree (status, refund_next_attempt_at, refund_claimed_until, updated_at) WHERE (status = 'refunding'::text);



CREATE INDEX idx_deposit_vaults_status ON public.deposit_vaults USING btree (status);



CREATE INDEX idx_deposit_vaults_timeout_refund_claimable ON public.deposit_vaults USING btree (cancel_after, status) WHERE (status = ANY (ARRAY['pending_funding'::text, 'funded'::text]));



CREATE INDEX idx_market_order_quotes_expires_at ON public.market_order_quotes USING btree (expires_at);



CREATE UNIQUE INDEX idx_market_order_quotes_order_id ON public.market_order_quotes USING btree (order_id);



CREATE UNIQUE INDEX idx_order_execution_attempts_order_active ON public.order_execution_attempts USING btree (order_id) WHERE (status = ANY (ARRAY['planning'::text, 'active'::text]));



CREATE UNIQUE INDEX idx_order_execution_attempts_order_attempt_index ON public.order_execution_attempts USING btree (order_id, attempt_index);



CREATE INDEX idx_order_execution_attempts_order_id ON public.order_execution_attempts USING btree (order_id);



CREATE INDEX idx_order_execution_attempts_status_updated_at ON public.order_execution_attempts USING btree (status, updated_at);



CREATE INDEX idx_order_execution_steps_attempt_id ON public.order_execution_steps USING btree (execution_attempt_id) WHERE (execution_attempt_id IS NOT NULL);



CREATE UNIQUE INDEX idx_order_execution_steps_attempt_index ON public.order_execution_steps USING btree (execution_attempt_id, step_index) WHERE (execution_attempt_id IS NOT NULL);



CREATE INDEX idx_order_execution_steps_order_id ON public.order_execution_steps USING btree (order_id);



CREATE UNIQUE INDEX idx_order_execution_steps_order_wait_step ON public.order_execution_steps USING btree (order_id, step_index) WHERE (execution_attempt_id IS NULL);



CREATE INDEX idx_order_execution_steps_status_next_attempt ON public.order_execution_steps USING btree (status, next_attempt_at) WHERE (status = ANY (ARRAY['planned'::text, 'waiting'::text, 'ready'::text, 'running'::text]));



CREATE INDEX idx_order_provider_addresses_chain_address ON public.order_provider_addresses USING btree (chain_id, address);



CREATE INDEX idx_order_provider_addresses_operation_id ON public.order_provider_addresses USING btree (provider_operation_id) WHERE (provider_operation_id IS NOT NULL);



CREATE INDEX idx_order_provider_addresses_order_id ON public.order_provider_addresses USING btree (order_id);



CREATE UNIQUE INDEX idx_order_provider_addresses_order_provider_role_chain_address ON public.order_provider_addresses USING btree (order_id, provider, role, chain_id, address);



CREATE INDEX idx_order_provider_addresses_step_id ON public.order_provider_addresses USING btree (execution_step_id) WHERE (execution_step_id IS NOT NULL);



CREATE UNIQUE INDEX idx_order_provider_operation_hints_idempotency_key ON public.order_provider_operation_hints USING btree (source, idempotency_key) WHERE (idempotency_key IS NOT NULL);



CREATE INDEX idx_order_provider_operation_hints_operation_id ON public.order_provider_operation_hints USING btree (provider_operation_id, created_at);



CREATE INDEX idx_order_provider_operation_hints_pending ON public.order_provider_operation_hints USING btree (status, created_at) WHERE (status = ANY (ARRAY['pending'::text, 'processing'::text]));



CREATE INDEX idx_order_provider_operations_order_id ON public.order_provider_operations USING btree (order_id);



CREATE UNIQUE INDEX idx_order_provider_operations_provider_ref ON public.order_provider_operations USING btree (provider, provider_ref) WHERE (provider_ref IS NOT NULL);



CREATE INDEX idx_order_provider_operations_status ON public.order_provider_operations USING btree (status, updated_at) WHERE (status = ANY (ARRAY['planned'::text, 'submitted'::text, 'waiting_external'::text]));



CREATE INDEX idx_order_provider_operations_step_id ON public.order_provider_operations USING btree (execution_step_id) WHERE (execution_step_id IS NOT NULL);



CREATE INDEX idx_paymaster_gas_ledger_order_id ON public.paymaster_gas_ledger USING btree (order_id);



CREATE INDEX idx_paymaster_gas_ledger_status ON public.paymaster_gas_ledger USING btree (status, updated_at);



CREATE INDEX idx_paymaster_gas_ledger_step_id ON public.paymaster_gas_ledger USING btree (execution_step_id) WHERE (execution_step_id IS NOT NULL);



CREATE INDEX idx_router_orders_funding_vault_id ON public.router_orders USING btree (funding_vault_id) WHERE (funding_vault_id IS NOT NULL);



CREATE UNIQUE INDEX idx_router_orders_idempotency_key ON public.router_orders USING btree (idempotency_key) WHERE (idempotency_key IS NOT NULL);



CREATE INDEX idx_router_orders_status_timeout ON public.router_orders USING btree (status, action_timeout_at);



CREATE INDEX idx_router_route_cost_snapshots_active ON public.router_route_cost_snapshots USING btree (expires_at, amount_bucket);



CREATE INDEX idx_router_worker_leases_expires_at ON public.router_worker_leases USING btree (expires_at);



CREATE TRIGGER update_custody_vaults_updated_at BEFORE UPDATE ON public.custody_vaults FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();



CREATE TRIGGER update_deposit_vault_funding_hints_updated_at BEFORE UPDATE ON public.deposit_vault_funding_hints FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();



CREATE TRIGGER update_deposit_vaults_updated_at BEFORE UPDATE ON public.deposit_vaults FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();



CREATE TRIGGER update_market_order_actions_updated_at BEFORE UPDATE ON public.market_order_actions FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();



CREATE TRIGGER update_order_execution_attempts_updated_at BEFORE UPDATE ON public.order_execution_attempts FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();



CREATE TRIGGER update_order_execution_steps_updated_at BEFORE UPDATE ON public.order_execution_steps FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();



CREATE TRIGGER update_order_provider_addresses_updated_at BEFORE UPDATE ON public.order_provider_addresses FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();



CREATE TRIGGER update_order_provider_operation_hints_updated_at BEFORE UPDATE ON public.order_provider_operation_hints FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();



CREATE TRIGGER update_order_provider_operations_updated_at BEFORE UPDATE ON public.order_provider_operations FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();



CREATE TRIGGER update_paymaster_gas_ledger_updated_at BEFORE UPDATE ON public.paymaster_gas_ledger FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();



CREATE TRIGGER update_router_orders_updated_at BEFORE UPDATE ON public.router_orders FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();



ALTER TABLE ONLY public.custody_vaults
    ADD CONSTRAINT custody_vaults_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.router_orders(id) ON DELETE CASCADE;



ALTER TABLE ONLY public.deposit_vault_funding_hints
    ADD CONSTRAINT deposit_vault_funding_hints_vault_id_fkey FOREIGN KEY (vault_id) REFERENCES public.deposit_vaults(id) ON DELETE CASCADE;



ALTER TABLE ONLY public.deposit_vaults
    ADD CONSTRAINT deposit_vaults_custody_vault_fkey FOREIGN KEY (id) REFERENCES public.custody_vaults(id) ON DELETE CASCADE;



ALTER TABLE ONLY public.market_order_actions
    ADD CONSTRAINT market_order_actions_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.router_orders(id) ON DELETE CASCADE;



ALTER TABLE ONLY public.market_order_quotes
    ADD CONSTRAINT market_order_quotes_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.router_orders(id) ON DELETE CASCADE;



ALTER TABLE ONLY public.order_execution_attempts
    ADD CONSTRAINT order_execution_attempts_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.router_orders(id) ON DELETE CASCADE;



ALTER TABLE ONLY public.order_execution_attempts
    ADD CONSTRAINT order_execution_attempts_trigger_provider_operation_id_fkey FOREIGN KEY (trigger_provider_operation_id) REFERENCES public.order_provider_operations(id) ON DELETE SET NULL;



ALTER TABLE ONLY public.order_execution_attempts
    ADD CONSTRAINT order_execution_attempts_trigger_step_id_fkey FOREIGN KEY (trigger_step_id) REFERENCES public.order_execution_steps(id) ON DELETE SET NULL;



ALTER TABLE ONLY public.order_execution_steps
    ADD CONSTRAINT order_execution_steps_execution_attempt_id_fkey FOREIGN KEY (execution_attempt_id) REFERENCES public.order_execution_attempts(id) ON DELETE CASCADE;



ALTER TABLE ONLY public.order_execution_steps
    ADD CONSTRAINT order_execution_steps_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.router_orders(id) ON DELETE CASCADE;



ALTER TABLE ONLY public.order_provider_addresses
    ADD CONSTRAINT order_provider_addresses_execution_step_id_fkey FOREIGN KEY (execution_step_id) REFERENCES public.order_execution_steps(id) ON DELETE SET NULL;



ALTER TABLE ONLY public.order_provider_addresses
    ADD CONSTRAINT order_provider_addresses_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.router_orders(id) ON DELETE CASCADE;



ALTER TABLE ONLY public.order_provider_addresses
    ADD CONSTRAINT order_provider_addresses_provider_operation_id_fkey FOREIGN KEY (provider_operation_id) REFERENCES public.order_provider_operations(id) ON DELETE SET NULL;



ALTER TABLE ONLY public.order_provider_operation_hints
    ADD CONSTRAINT order_provider_operation_hints_provider_operation_id_fkey FOREIGN KEY (provider_operation_id) REFERENCES public.order_provider_operations(id) ON DELETE CASCADE;



ALTER TABLE ONLY public.order_provider_operations
    ADD CONSTRAINT order_provider_operations_execution_attempt_id_fkey FOREIGN KEY (execution_attempt_id) REFERENCES public.order_execution_attempts(id) ON DELETE SET NULL;



ALTER TABLE ONLY public.order_provider_operations
    ADD CONSTRAINT order_provider_operations_execution_step_id_fkey FOREIGN KEY (execution_step_id) REFERENCES public.order_execution_steps(id) ON DELETE SET NULL;



ALTER TABLE ONLY public.order_provider_operations
    ADD CONSTRAINT order_provider_operations_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.router_orders(id) ON DELETE CASCADE;



ALTER TABLE ONLY public.paymaster_gas_ledger
    ADD CONSTRAINT paymaster_gas_ledger_execution_attempt_id_fkey FOREIGN KEY (execution_attempt_id) REFERENCES public.order_execution_attempts(id) ON DELETE SET NULL;



ALTER TABLE ONLY public.paymaster_gas_ledger
    ADD CONSTRAINT paymaster_gas_ledger_execution_step_id_fkey FOREIGN KEY (execution_step_id) REFERENCES public.order_execution_steps(id) ON DELETE SET NULL;



ALTER TABLE ONLY public.paymaster_gas_ledger
    ADD CONSTRAINT paymaster_gas_ledger_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.router_orders(id) ON DELETE CASCADE;



ALTER TABLE ONLY public.router_orders
    ADD CONSTRAINT router_orders_funding_vault_id_fkey FOREIGN KEY (funding_vault_id) REFERENCES public.deposit_vaults(id);




