-- Per-request route-cost sampling activity feed. Each row is one provider
-- sample attempt made by the paced refresher (one (transition, tier) unit).
-- Powers the admin dashboard activity log + schedule timeline. This table is
-- best-effort and pruned to a short retention window by the writer; it is not
-- on any quote-time read path.
CREATE TABLE public.router_route_cost_sample_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sampled_at timestamp with time zone NOT NULL,
    provider text NOT NULL,
    transition_id text NOT NULL,
    amount_bucket text NOT NULL,
    edge_kind text NOT NULL,
    source_chain text NOT NULL,
    source_asset text NOT NULL,
    destination_chain text NOT NULL,
    destination_asset text NOT NULL,
    sample_amount_usd_micros bigint NOT NULL,
    outcome text NOT NULL,
    estimated_fee_bps bigint,
    estimated_latency_ms bigint,
    reason text,
    CONSTRAINT router_route_cost_sample_events_outcome_check
        CHECK (outcome IN ('succeeded', 'failed')),
    CONSTRAINT router_route_cost_sample_events_sample_amount_usd_micros_check
        CHECK (sample_amount_usd_micros > 0)
);

CREATE INDEX idx_route_cost_sample_events_recent
    ON public.router_route_cost_sample_events USING btree (sampled_at DESC);

CREATE INDEX idx_route_cost_sample_events_provider_recent
    ON public.router_route_cost_sample_events USING btree (provider, sampled_at DESC);
