// @generated by scripts/gen-single-hop-assets.py; do not edit by hand.
// Source: https://api.garden.finance/v2/chains

use crate::services::{
    asset_registry::ProviderId,
    single_hop_assets::{
        RouterAssetKind, VenueAssetEntry, VenueAssetMapSpec, VenueAssetPolicy, VenueChainAssetsSpec,
    },
};

const GARDEN_BITCOIN_ASSETS: &[VenueAssetEntry] = &[VenueAssetEntry {
    router_asset: RouterAssetKind::Native,
    venue_asset: "btc",
}];

const GARDEN_EVM_1_ASSETS: &[VenueAssetEntry] = &[
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x2260fac5e5542a773aa44fbcfedf7c193bc2c599"),
        venue_asset: "wbtc",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"),
        venue_asset: "usdc",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xcbb7c0000ab88b473b1f5afd9ef808440eed33bf"),
        venue_asset: "cbbtc",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xdac17f958d2ee523a2206206994597c13d831ec7"),
        venue_asset: "usdt",
    },
];

const GARDEN_EVM_42161_ASSETS: &[VenueAssetEntry] = &[
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x050c24dbf1eec17babe5fc585f06116a259cc77a"),
        venue_asset: "ibtc",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f"),
        venue_asset: "wbtc",
    },
];

const GARDEN_EVM_8453_ASSETS: &[VenueAssetEntry] = &[
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xcb17c9db87b595717c857a08468793f5bab6445f"),
        venue_asset: "cbltc",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xcbb7c0000ab88b473b1f5afd9ef808440eed33bf"),
        venue_asset: "cbbtc",
    },
];

const GARDEN_CHAINS: &[VenueChainAssetsSpec] = &[
    VenueChainAssetsSpec {
        router_chain: "bitcoin",
        venue_chain: "bitcoin",
        asset_policy: VenueAssetPolicy::ListedOnly,
        assets: GARDEN_BITCOIN_ASSETS,
    },
    VenueChainAssetsSpec {
        router_chain: "evm:1",
        venue_chain: "ethereum",
        asset_policy: VenueAssetPolicy::ListedOnly,
        assets: GARDEN_EVM_1_ASSETS,
    },
    VenueChainAssetsSpec {
        router_chain: "evm:42161",
        venue_chain: "arbitrum",
        asset_policy: VenueAssetPolicy::ListedOnly,
        assets: GARDEN_EVM_42161_ASSETS,
    },
    VenueChainAssetsSpec {
        router_chain: "evm:8453",
        venue_chain: "base",
        asset_policy: VenueAssetPolicy::ListedOnly,
        assets: GARDEN_EVM_8453_ASSETS,
    },
];

pub const GARDEN_ASSET_MAP_SPEC: VenueAssetMapSpec = VenueAssetMapSpec {
    provider: ProviderId::Garden,
    chains: GARDEN_CHAINS,
};
