// @generated by scripts/gen-single-hop-assets.py; do not edit by hand.
// Source: https://chainflip-swap.chainflip.io/api/networkInfo plus official Chainflip asset constants

use crate::services::{
    asset_registry::ProviderId,
    single_hop_assets::{
        RouterAssetKind, VenueAssetEntry, VenueAssetMapSpec, VenueAssetPolicy, VenueChainAssetsSpec,
    },
};

const CHAINFLIP_BITCOIN_ASSETS: &[VenueAssetEntry] = &[VenueAssetEntry {
    router_asset: RouterAssetKind::Native,
    venue_asset: "BTC",
}];

const CHAINFLIP_EVM_1_ASSETS: &[VenueAssetEntry] = &[
    VenueAssetEntry {
        router_asset: RouterAssetKind::Native,
        venue_asset: "ETH",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x2260fac5e5542a773aa44fbcfedf7c193bc2c599"),
        venue_asset: "WBTC",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x826180541412d574cf1336d22c0c0a287822678a"),
        venue_asset: "FLIP",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"),
        venue_asset: "USDC",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xdac17f958d2ee523a2206206994597c13d831ec7"),
        venue_asset: "USDT",
    },
];

const CHAINFLIP_EVM_42161_ASSETS: &[VenueAssetEntry] = &[
    VenueAssetEntry {
        router_asset: RouterAssetKind::Native,
        venue_asset: "ETH",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xaf88d065e77c8cc2239327c5edb3a432268e5831"),
        venue_asset: "USDC",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xfd086bc7cd5c481dcc9c85ebe478a1c0b69fcbb9"),
        venue_asset: "USDT",
    },
];

const CHAINFLIP_CHAINS: &[VenueChainAssetsSpec] = &[
    VenueChainAssetsSpec {
        router_chain: "bitcoin",
        venue_chain: "Bitcoin",
        asset_policy: VenueAssetPolicy::ListedOnly,
        assets: CHAINFLIP_BITCOIN_ASSETS,
    },
    VenueChainAssetsSpec {
        router_chain: "evm:1",
        venue_chain: "Ethereum",
        asset_policy: VenueAssetPolicy::ListedOnly,
        assets: CHAINFLIP_EVM_1_ASSETS,
    },
    VenueChainAssetsSpec {
        router_chain: "evm:42161",
        venue_chain: "Arbitrum",
        asset_policy: VenueAssetPolicy::ListedOnly,
        assets: CHAINFLIP_EVM_42161_ASSETS,
    },
];

pub const CHAINFLIP_ASSET_MAP_SPEC: VenueAssetMapSpec = VenueAssetMapSpec {
    provider: ProviderId::Chainflip,
    chains: CHAINFLIP_CHAINS,
};
