// @generated by scripts/gen-single-hop-assets.py; do not edit by hand.
// Source: https://api.relay.link/chains

use crate::services::{
    asset_registry::ProviderId,
    single_hop_assets::{
        ContractEncoding, ContractPassthrough, ContractStandard, RouterAssetKind, VenueAssetEntry,
        VenueAssetMapSpec, VenueAssetPolicy, VenueChainAssetsSpec,
    },
};

const RELAY_EVM_CONTRACT_PASSTHROUGH: ContractPassthrough = ContractPassthrough {
    standard: ContractStandard::Erc20,
    encoding: ContractEncoding::LowercaseHex,
};

const RELAY_EVM_1_ASSETS: &[VenueAssetEntry] = &[VenueAssetEntry {
    router_asset: RouterAssetKind::Native,
    venue_asset: "0x0000000000000000000000000000000000000000",
}];

const RELAY_EVM_42161_ASSETS: &[VenueAssetEntry] = &[VenueAssetEntry {
    router_asset: RouterAssetKind::Native,
    venue_asset: "0x0000000000000000000000000000000000000000",
}];

const RELAY_EVM_8453_ASSETS: &[VenueAssetEntry] = &[VenueAssetEntry {
    router_asset: RouterAssetKind::Native,
    venue_asset: "0x0000000000000000000000000000000000000000",
}];

const RELAY_BITCOIN_ASSETS: &[VenueAssetEntry] = &[VenueAssetEntry {
    router_asset: RouterAssetKind::Native,
    venue_asset: "bc1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqmql8k8",
}];

const RELAY_CHAINS: &[VenueChainAssetsSpec] = &[
    VenueChainAssetsSpec {
        router_chain: "evm:1",
        venue_chain: "1",
        asset_policy: VenueAssetPolicy::ListedPlusOpenContracts(RELAY_EVM_CONTRACT_PASSTHROUGH),
        assets: RELAY_EVM_1_ASSETS,
    },
    VenueChainAssetsSpec {
        router_chain: "evm:42161",
        venue_chain: "42161",
        asset_policy: VenueAssetPolicy::ListedPlusOpenContracts(RELAY_EVM_CONTRACT_PASSTHROUGH),
        assets: RELAY_EVM_42161_ASSETS,
    },
    VenueChainAssetsSpec {
        router_chain: "evm:8453",
        venue_chain: "8453",
        asset_policy: VenueAssetPolicy::ListedPlusOpenContracts(RELAY_EVM_CONTRACT_PASSTHROUGH),
        assets: RELAY_EVM_8453_ASSETS,
    },
    VenueChainAssetsSpec {
        router_chain: "bitcoin",
        venue_chain: "8253038",
        asset_policy: VenueAssetPolicy::ListedOnly,
        assets: RELAY_BITCOIN_ASSETS,
    },
];

pub const RELAY_ASSET_MAP_SPEC: VenueAssetMapSpec = VenueAssetMapSpec {
    provider: ProviderId::Relay,
    chains: RELAY_CHAINS,
};
