// @generated by scripts/gen-single-hop-assets.py; do not edit by hand.
// Source: https://api.changenow.io/v2/exchange/currencies?active=true

use crate::services::{
    asset_registry::ProviderId,
    single_hop_assets::{
        RouterAssetKind, VenueAssetEntry, VenueAssetMapSpec, VenueAssetPolicy, VenueChainAssetsSpec,
    },
};

const CHANGENOW_BITCOIN_ASSETS: &[VenueAssetEntry] = &[VenueAssetEntry {
    router_asset: RouterAssetKind::Native,
    venue_asset: "btc",
}];

const CHANGENOW_EVM_1_ASSETS: &[VenueAssetEntry] = &[
    VenueAssetEntry {
        router_asset: RouterAssetKind::Native,
        venue_asset: "eth",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x0000000000085d4780b73119b644ae5ecd22b376"),
        venue_asset: "tusd",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x0000000000095413afc295d19edeb1ad7b71c952"),
        venue_asset: "lon",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x000000fa00b200406de700041cfc6b19bbfb4d13"),
        venue_asset: "towns",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x000006c2a22ff4a44ff1f5d0f2ed65f781f55555"),
        venue_asset: "zkc",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x00b78238925c320159023c2ac9ef89da8f16d007"),
        venue_asset: "vps",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x00c83aecc790e8a4453e5dd3b0b4b3680501a7a7"),
        venue_asset: "skl",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x01791f726b4103694969820be083196cc7c045ff"),
        venue_asset: "yb",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x01ff50f8b7f74e4f00580d9596cd3d0d6d6e326f"),
        venue_asset: "bft",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x0202be363b8a4820f3f4de7faf5224ff05943ab1"),
        venue_asset: "uft",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x031de51f3e8016514bd0963d0b2ab825a591db9a"),
        venue_asset: "esp",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x037a54aab062628c9bbae1fdb1583c195585fe41"),
        venue_asset: "lcx",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x0391d2021f89dc339f60fff84546ea23e337750f"),
        venue_asset: "bond",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x046bad07658f3b6cad9a396cfcbc1243af452ec1"),
        venue_asset: "al",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x0488401c3f535193fa8df029d9ffe615a06e74e6"),
        venue_asset: "srk",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x04fa0d235c4abf4bcf4787af4cf447de572ef828"),
        venue_asset: "uma",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x056fd409e1d7a124bd7017459dfea2f387b6d5cd"),
        venue_asset: "gusd",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x07041776f5007aca2a54844f50503a18a72a8b68"),
        venue_asset: "usat",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x081131434f93063751813c619ecca9c4dc7862a3"),
        venue_asset: "dar",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x086f405146ce90135750bbec9a063a8b20a8bffb"),
        venue_asset: "brev",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x08dcb9b5989fb09ef80e85567ec1f49577a70d29"),
        venue_asset: "a2z",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x090185f2135308bad17527004364ebcc2d37e5f6"),
        venue_asset: "spell",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x0a6e7ba5042b38349e437ec6db6214aec7b35676"),
        venue_asset: "swell",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x0b010000b7624eb9b3dfbc279673c76e9d29d5f7"),
        venue_asset: "obol",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x0b38210ea11411557c13457d4da7dc6ea731b88a"),
        venue_asset: "api3",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x0bb217e40f8a5cb79adf04e1aab60e5abd0dfc1e"),
        venue_asset: "swftc",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x0bc529c00c6401aef6d220be8c6ea1667f6ad93e"),
        venue_asset: "yfi",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x0ccae1bc46fb018dd396ed4c45565d4cb9d41098"),
        venue_asset: "misha",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x0d438f3b5175bebc262bf23753c1e53d03432bde"),
        venue_asset: "wnxm",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x0d8775f648430679a709e98d2b0cb6250d2887ef"),
        venue_asset: "bat",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x0e397938c1aa0680954093495b70a9f5e2249aba"),
        venue_asset: "qqqon",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x0e8d6b471e332f140e7d9dbb99e5e3822f728da6"),
        venue_asset: "abyss",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x0f2d719407fdbeff09d87557abb7232601fd9f29"),
        venue_asset: "syn",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x0f51bb10119727a7e5ea3538074fb341f56b09ad"),
        venue_asset: "dao",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x0f5d2fb29fb7d3cfee444a200298f468908cc942"),
        venue_asset: "mana",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x0f7f961648ae6db43c75663ac7e5414eb79b5704"),
        venue_asset: "xio",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x0fc2a55d5bd13033f1ee0cdd11f60f7efe66f467"),
        venue_asset: "la",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x0fd10b9899882a6f2fcb5c371e17e70fdee00c38"),
        venue_asset: "pundix",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x106552c11272420aad5d7e94f8acab9095a6c952"),
        venue_asset: "keanu",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x10dea67478c5f8c5e2d90e5e9b26dbe60c54d800"),
        venue_asset: "taiko",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x111111111117dc0aa78b770fa6a738034120c302"),
        venue_asset: "1inch",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x1121acc14c63f3c872bfca497d10926a6098aac5"),
        venue_asset: "doge",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x115ec79f1de567ec68b7ae7eda501b406626478e"),
        venue_asset: "cre",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x118b552725e1892137740cb4d29390d952709639"),
        venue_asset: "nyxt",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x11eef04c884e24d9b7b4760e7476d06ddf797f36"),
        venue_asset: "mx",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x12970e6868f88f6557b76120662c1b3e50a646bf"),
        venue_asset: "ladys",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x12bb890508c125661e03b09ec06e404bc9289040"),
        venue_asset: "raca",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x14778860e937f509e651192a90589de711fb88a9"),
        venue_asset: "cyber",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x1494ca1f11d487c2bbe4543e90080aeba4ba3c2b"),
        venue_asset: "dpi",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x1495bc9e44af1f8bcb62278d2bec4540cf0c05ea"),
        venue_asset: "deai",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x14c3abf95cb9c93a8b82c1cdcb76d72cb87b2d4c"),
        venue_asset: "aaplon",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x14fee680690900ba0cccfc76ad70fd1b95d10e16"),
        venue_asset: "paal",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x152649ea73beab28c5b49b26eb48f7ead6d4c898"),
        venue_asset: "cake",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x163f8c2467924be0ae7b5347228cabf260318753"),
        venue_asset: "wld",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x17205fab260a7a6383a81452ce6315a39370db97"),
        venue_asset: "rave",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x1776e1f26f98b1a5df9cd347953a26dd3cb46671"),
        venue_asset: "nmr",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x18aaa7115705e8be94bffebde57af9bfc265b998"),
        venue_asset: "audio",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x193f4a4a6ea24102f49b931deeeb931f6e32405d"),
        venue_asset: "tlos",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x1a3496c18d558bd9c6c8f609e1b129f67ab08163"),
        venue_asset: "dep",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x1abaea1f7c830bd89acc67ec4af516284b1bc33c"),
        venue_asset: "eurc",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x1bbe973bef3a977fc51cbed703e8ffdefe001fed"),
        venue_asset: "portal",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x1cc7047e15825f639e0752eb1b89e4225f5327f2"),
        venue_asset: "plx",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x1ce270557c1f68cfb577b856766310bf8b47fd9c"),
        venue_asset: "mong",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x1ceb5cb57c4d4e2b2433641b95dd330a33185a44"),
        venue_asset: "kp3r",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x1dd80016e3d4ae146ee2ebb484e8edd92dacc4ce"),
        venue_asset: "lead",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x1f573d6fb3f13d689ff844b4ce37794d79a7ff1c"),
        venue_asset: "bnt",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x1f57da732a77636d913c9a75d685b26cc85dcc3a"),
        venue_asset: "ol",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x1f9840a85d5af5bf1d1762f925bdaddc4201f984"),
        venue_asset: "uni",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x221657776846890989a759ba2973e427dff5c9bb"),
        venue_asset: "rep",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x2260fac5e5542a773aa44fbcfedf7c193bc2c599"),
        venue_asset: "wbtc",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x232ce3bd40fcd6f80f3d55a522d03f25df784ee2"),
        venue_asset: "lit",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x246908bff0b1ba6ecadcf57fb94f6ae2fcd43a77"),
        venue_asset: "divi",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x249ca82617ec3dfb2589c4c17ab7ec9765350a18"),
        venue_asset: "verse",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x249e38ea4102d0cf8264d3701f1a0e39c4f2dc3b"),
        venue_asset: "ufo",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x24a3d725c37a8d1a66eb87f0e5d07fe67c120035"),
        venue_asset: "eden",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x24fcfc492c1393274b6bcd568ac9e225bec93584"),
        venue_asset: "mavia",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x2559813bbb508c4c79e9ccce4703bcb1f149edd7"),
        venue_asset: "wait",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x25931894a86d47441213199621f1f2994e1c39aa"),
        venue_asset: "cgpt",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x259338656198ec7a76c729514d3cb45dfbf768a1"),
        venue_asset: "resolv",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x25f8087ead173b73d6e8b84329989a8eea16cf73"),
        venue_asset: "ygg",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x26c8afbbfe1ebaca03c2bb082e69d0476bffe099"),
        venue_asset: "cell",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x26e550ac11b26f78a04489d5f20f24e3559f7dd9"),
        venue_asset: "kekius",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x27054b13b1b798b345b591a4d22e6562d47ea75a"),
        venue_asset: "ast",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x27c70cd1946795b66be9d954418546998b546634"),
        venue_asset: "leash",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x28561b8a2360f463011c16b6cc0b0cbef8dbbcad"),
        venue_asset: "moodeng",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x28d38df637db75533bd3f71426f3410a82041544"),
        venue_asset: "prompt",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x2a3bff78b79a009976eea096a51a948a3dc00e34"),
        venue_asset: "wild",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x2a8e1e676ec238d8a992307b495b45b3feaa5e86"),
        venue_asset: "ousd",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x2ad9addd0d97ec3cdba27f92bf6077893b76ab0b"),
        venue_asset: "planet",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x2af5d2ad76741191d15dfe7bf6ac92d4bd912ca3"),
        venue_asset: "leo",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x2b591e99afe9f32eaa6214f7b7629768c40eeb39"),
        venue_asset: "hex",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x2ba592f78db6436527729929aaf6c908497cb200"),
        venue_asset: "cream",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x2d1f7226bd1f780af6b9a49dcc0ae00e8df4bdee"),
        venue_asset: "nvdaon",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x2dff88a56767223a5529ea5960da7a3f5f766406"),
        venue_asset: "id",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x2ee7097bfdd98fce2ac08a1896038a7cd9aaed81"),
        venue_asset: "gaia",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x3010ccb5419f1ef26d40a7cd3f0d707a0fa127dc"),
        venue_asset: "gems",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x3073f7aaa4db83f95e9fff17424f71d4751a3073"),
        venue_asset: "move",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x30a25cc9c9eade4d4d9e9349be6e68c3411367d3"),
        venue_asset: "ptb",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x30d20208d987713f46dfd34ef128bb16c404d10f"),
        venue_asset: "sd",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x31c8eacbffdd875c74b94b077895bd78cf1e64a3"),
        venue_asset: "rad",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x320623b8e4ff03373931769a31fc52a4e78b5d70"),
        venue_asset: "rsr",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x32353a6c91143bfd6c7d363b546e62a9a2489a20"),
        venue_asset: "agld",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x32b4d049fe4c888d2b92eecaf729f44df6b1f36e"),
        venue_asset: "robo",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x32b86b99441480a7e5bd3a26c124ec2373e3f015"),
        venue_asset: "bad",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x33b481cbbf3c24f2b3184ee7cb02daad1c4f49a8"),
        venue_asset: "d",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x3429d03c6f7521aec737a0bbf2e5ddcef2c3ae31"),
        venue_asset: "pixel",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x3472a5a71965499acd81997a54bba8d852c6e53d"),
        venue_asset: "badger",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x34950ff2b487d9e5282c5ab342d08a2f712eb79f"),
        venue_asset: "wozx",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x3506424f91fd33084466f402d5d97f05f8e3b4af"),
        venue_asset: "chz",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x3597bfd533a99c9aa083587b074434e61eb0a258"),
        venue_asset: "dent",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x3632dea96a953c11dac2f00b4a05a32cd1063fae"),
        venue_asset: "crclon",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x3802c218221390025bceabbad5d8c59f40eb74b8"),
        venue_asset: "geth",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x382ea807a61a418479318efd96f1efbc5c1f2c21"),
        venue_asset: "pew",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x3845badade8e6dff049820680d1f14bd3903a5d0"),
        venue_asset: "sand",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x38e68a37e401f7271568cecaac63c6b1e19130b4"),
        venue_asset: "banana",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x3b50805453023a91a8bf641e279401a0b23fa6f9"),
        venue_asset: "rez",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x3b991130eae3cca364406d718da22fa1c3e7c256"),
        venue_asset: "shrub",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x3c3a81e81dc49a522a592e7622a7e711c06bf354"),
        venue_asset: "mnt",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x3c4b6e6e1ea3d4863700d7f76b36b7f3d3f13e3d"),
        venue_asset: "vgx",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x3da932456d082cba208feb0b096d49b202bf89c8"),
        venue_asset: "dego",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x3e5a19c91266ad8ce2477b91585d1856b84062df"),
        venue_asset: "a8",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x3e76dd57e649a263a532cc9bcc58b32a065fb2a4"),
        venue_asset: "acn",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x3e9bc21c9b189c09df3ef1b824798658d5011937"),
        venue_asset: "lina",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x3ee4b152824b657644c7a9b50694787e80eb8f4a"),
        venue_asset: "bazed",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x3f382dbd960e3a9bbceae22651e88158d2791550"),
        venue_asset: "ghst",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x3f80b1c54ae920be41a77f8b902259d48cf24ccf"),
        venue_asset: "kernel",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x3ffeea07a27fab7ad1df5297fa75e77a43cb5790"),
        venue_asset: "peipei",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x41545f8b9472d758bb669ed8eaeeecd7a9c4ec29"),
        venue_asset: "fort",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x419d0d8bdd9af5e606ae2232ed285aff190e711b"),
        venue_asset: "fun",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x41e5560054824ea6b0732e656e3ad64e20e94e45"),
        venue_asset: "cvc",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x42069026eac8eee0fd9b5f7adfa4f6e6d69a2b39"),
        venue_asset: "mstr",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x423f4e6138e475d85cf7ea071ac92097ed631eea"),
        venue_asset: "pndc",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x42bbfa2e77757c645eeaad1655e0911a7553efbc"),
        venue_asset: "boba",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x430ef9263e76dae63c84292c3409d61c598e9682"),
        venue_asset: "pyr",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x43dfc4159d86f3a37a5a4b3d4580b888ad7d4ddd"),
        venue_asset: "dodo",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x44108f0223a3c3028f5fe7aec7f9bb2e66bef82f"),
        venue_asset: "acx",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x441761326490cacf7af299725b6292597ee822c2"),
        venue_asset: "unfi",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x442b153f6f61c0c99a33aa4170dcb31e1abda1d0"),
        venue_asset: "ava",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x44f49ff0da2498bcb1d3dc7c0f999578f67fd8c6"),
        venue_asset: "corn",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x44ff8620b8ca30902395a7bd3f2407e1a091bf73"),
        venue_asset: "virtual",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x4507cef57c46789ef8d1a19ea45f4216bae2b528"),
        venue_asset: "token",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x455e53cbb86018ac2b8092fdcd39d8444affc3f6"),
        venue_asset: "pol",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x4575f41308ec1483f3d399aa9a2826d74da13deb"),
        venue_asset: "oxt",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x45804880de22913dafe09f4980848ece6ecbaf78"),
        venue_asset: "paxg",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x467bccd9d29f223bce8043b84e8c8b282827790f"),
        venue_asset: "tel",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x4691937a7508860f876c9c0a2a617e7d9e945d4b"),
        venue_asset: "woo",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x476c5e26a75bd202a9683ffd34359c0cc15be0ff"),
        venue_asset: "srm",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x485d17a6f1b8780392d53d64751824253011a260"),
        venue_asset: "time",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x491604c0fdf08347dd1fa4ee062a822a5dd06b5d"),
        venue_asset: "ctsi",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x4947b72fed037ade3365da050a9be5c063e605a7"),
        venue_asset: "peanut",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x49642110b712c1fd7261bc074105e9e44676c68f"),
        venue_asset: "dino",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x4a220e6096b25eadb88358cb44068a3248254675"),
        venue_asset: "qnt",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x4b5f49487ea7b3609b1ad05459be420548789f1f"),
        venue_asset: "lever",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x4b9278b94a1112cad404048903b8d343a810b07e"),
        venue_asset: "hifi",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x4c1746a800d224393fe2470c70a35717ed4ea5f1"),
        venue_asset: "plume",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x4c19596f5aaff459fa38b0f7ed92f11ae6543784"),
        venue_asset: "tru",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x4c9edd5852cd905f086c759e8383e09bff1e68b3"),
        venue_asset: "usde",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x4d1c297d39c5c1277964d0e3f8aa901493664530"),
        venue_asset: "puffer",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x4d224452801aced8b2f0aebe155379bb5d594381"),
        venue_asset: "ape",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x4db26817c88a57d2ef84cfd90168f535ee83bda9"),
        venue_asset: "hiazuki",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x4dc26fc5854e7648a064a4abd590bbe71724c277"),
        venue_asset: "anime",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x4e3fbd56cd56c3e72c1403e103b45db9da5b9d2b"),
        venue_asset: "cvx",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x4f0ca3df1c2e6b943cf82e649d576ffe7b2fabcf"),
        venue_asset: "iauon",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x4f2b33840227ddd0e28da8d4185d6fa07adfed87"),
        venue_asset: "based",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x4f9254c83eb525f9fcf346490bbb3ed28a81c667"),
        venue_asset: "celr",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x5026f006b85729a8b14553fae6af249ad16c9aab"),
        venue_asset: "wojak",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x50d1c9771902476076ecfc8b2a83ad6b9355a4c9"),
        venue_asset: "ftt",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x514910771af9ca656af840dff83e8264ecf986ca"),
        venue_asset: "link",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x51db5ad35c671a87207d88fc11d593ac0c8415bd"),
        venue_asset: "mda",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x52498f8d9791736f1d6398fe95ba3bd868114d10"),
        venue_asset: "netvr",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x52662717e448be36cb54588499d5a8328bd95292"),
        venue_asset: "tenshi",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x5283d291dbcf85356a21ba090e6db59121208b44"),
        venue_asset: "blur",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x52a8845df664d76c69d2eea607cd793565af42b8"),
        venue_asset: "apex",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x54012cdf4119de84218f7eb90eeb87e25ae6ebd7"),
        venue_asset: "luffy",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x54d2252757e1672eead234d27b1270728ff90581"),
        venue_asset: "bgb",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x55296f69f40ea6d20e478533c15a6b08b654e758"),
        venue_asset: "xyo",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x553f4cb7256d8fc038e91d36cb63fa7c13b624ab"),
        venue_asset: "tanssi",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x56072c95faa701256059aa122697b133aded9279"),
        venue_asset: "sky",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x56a3ba04e95d34268a19b2a4474dc979babdaf76"),
        venue_asset: "sent",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x5732046a883704404f284ce41ffadd5b007fd668"),
        venue_asset: "blz",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x579cea1889991f68acc35ff5c3dd0621ff29b0c9"),
        venue_asset: "iq",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x57ab1ec28d129707052df4df418d58a2d46d5f51"),
        venue_asset: "susd",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x57b946008913b82e4df85f501cbaed910e58d26c"),
        venue_asset: "pond",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x57e114b691db790c35207b2e685d4a43181e6061"),
        venue_asset: "ena",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x582d872a1b094fc48f5de31d3b73f2d9be47def1"),
        venue_asset: "ton",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x58b6a8a3302369daec383334672404ee733ab239"),
        venue_asset: "lpt",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x58b9cb810a68a7f3e1e4f8cb45d1b9b3c79705e8"),
        venue_asset: "clear",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x58d97b57bb95320f9a05dc918aef65434969c2b2"),
        venue_asset: "morpho",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x594daad7d77592a2b97b725a7ad59d7e188b5bfa"),
        venue_asset: "apu",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x595832f8fc6bf59c85c527fec3740a1b7a361269"),
        venue_asset: "powr",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x59644165402b611b350645555b50afb581c71eb2"),
        venue_asset: "metaon",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x5a98fcbea516cf06857215779fd812ca3bef1b32"),
        venue_asset: "ldo",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x5afe3855358e112b5647b952709e6165e1c1eeee"),
        venue_asset: "safe",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x5c8d0c48810fd37a0a824d074ee290e64f7a8fa2"),
        venue_asset: "avl",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x5f98805a4e8be255a32880fdec7f6728c6568ba0"),
        venue_asset: "lusd",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x6033f7f88332b8db6ad452b7c6d5bb643990ae3f"),
        venue_asset: "lsk",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x6055dc6ff1077eebe5e6d2ba1a1f53d7ef8430de"),
        venue_asset: "es",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x607f4c5bb672230e8672085532f7e901544a7375"),
        venue_asset: "rlc",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x60f5672a271c7e39e787427a18353ba59a4a3578"),
        venue_asset: "pika",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x61dbbbb552dc893ab3aad09f289f811e67cef285"),
        venue_asset: "skate",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x6226e00bcac68b0fe55583b90a1d727c14fab77f"),
        venue_asset: "mtv",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x62359ed7505efc61ff1d56fef82158ccaffa23d7"),
        venue_asset: "core",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x6243558a24cc6116abe751f27e6d7ede50abfc76"),
        venue_asset: "lvva",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x626e8036deb333b408be468f951bdb42433cbf18"),
        venue_asset: "aioz",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x628a3b2e302c7e896acc432d2d0dd22b6cb9bc88"),
        venue_asset: "lmwr",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x62d0a8458ed7719fdaf978fe5929c6d342b0bfce"),
        venue_asset: "beamx",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x643c4e15d7d62ad0abec4a9bd4b001aa3ef52d66"),
        venue_asset: "syrup",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x64bc2ca1be492be7185faa2c8835d9b824c8a194"),
        venue_asset: "bigtime",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x656c00e1bcd96f256f224ad9112ff426ef053733"),
        venue_asset: "efi",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x662b67d00a13faf93254714dd601f5ed49ef2f51"),
        venue_asset: "orc",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x66761fa41377003622aee3c7675fc7b5c1c2fac5"),
        venue_asset: "cpool",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x66a0f676479cee1d7373f3dc2e2952778bff5bd6"),
        venue_asset: "wise",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x67466be17df832165f8c80a5a120ccc652bd7e69"),
        venue_asset: "wolf",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x675b68aa4d9c2d3bb3f0397048e62e6b7192079c"),
        venue_asset: "fuel",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x6810e776880c02933d47db1b9fc05908e5386b96"),
        venue_asset: "gno",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x68749665ff8d2d112fa859aa293f07a622782f38"),
        venue_asset: "xaut",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x68a47fe1cf42eba4a030a10cd4d6a1031ca3ca0a"),
        venue_asset: "tet",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x68bbed6a47194eff1cf514b50ea91895597fc91e"),
        venue_asset: "andy",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x6982508145454ce325ddbe47a25d4ec3d2311933"),
        venue_asset: "pepe",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x6985884c4392d348587b19cb9eaaf157f13271cd"),
        venue_asset: "zro",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x699ccf919c1dfdfa4c374292f42cadc9899bf753"),
        venue_asset: "vsn",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x699f088b5dddcafb7c4824db5b10b57b37cb0c66"),
        venue_asset: "enso",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x69af81e73a73b40adf4f3d4223cd9b1ece623074"),
        venue_asset: "mask",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x6b0b3a982b4634ac68dd83a4dbf02311ce324181"),
        venue_asset: "ali",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x6b175474e89094c44da98b954eedeac495271d0f"),
        venue_asset: "dai",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x6b3595068778dd592e39a122f4f5a5cf09c90fe2"),
        venue_asset: "sushi",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x6bef15d938d4e72056ac92ea4bdd0d76b1c4ad29"),
        venue_asset: "prove",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x6c3ea9036406852006290770bedfcaba0e23a0e8"),
        venue_asset: "pyusd",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x6c5ba91642f10282b576d91922ae6448c9d52f4e"),
        venue_asset: "pha",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x6c6ee5e31d828de241282b9606c8e98ea48526e2"),
        venue_asset: "hot",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x6c76de483f1752ac8473e2b4983a873991e70da7"),
        venue_asset: "btr",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x6c936d4ae98e6d2172db18c16c4b601c99918ee6"),
        venue_asset: "life",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x6dea81c8171d0ba574754ef6f8b412f2ed88c54d"),
        venue_asset: "lqty",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x6e15a54b5ecac17e58dadeddbe8506a7560252f9"),
        venue_asset: "f",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x6e2a43be0b1d33b726f0ca3b8de60b3482b8b050"),
        venue_asset: "arkm",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x6e6f6d696e61decd6605bd4a57836c5db6923340"),
        venue_asset: "nom",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x6ecf5fe60e27cd03abdba3a19af8dc6845a0da58"),
        venue_asset: "bobaerc20",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x712bd4beb54c6b958267d9db0259abdbb0bff606"),
        venue_asset: "uds",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x71ab77b7dbb4fa7e017bc15090b2163221420282"),
        venue_asset: "high",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x720cd16b011b987da3518fbf38c3071d4f0d1495"),
        venue_asset: "flux",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x728f30fa2f100742c7949d1961804fa8e0b1387d"),
        venue_asset: "ghx",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x7420b4b9a0110cdc71fb720908340c03f9bc03ec"),
        venue_asset: "jasmy",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x7448c7456a97769f6cd04f1e83a4a23ccdc46abd"),
        venue_asset: "mav",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x744d70fdbe2ba4cf95131626614a1763df805b9e"),
        venue_asset: "snt",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x75231f58b43240c9718dd58b4967c5114342a86c"),
        venue_asset: "okb",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x761d38e5ddf6ccf6cf7c55759d5210750b5d60f3"),
        venue_asset: "elon",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x7636d8722fdf7cd34232a915e48e96aa3eb386bf"),
        venue_asset: "sfi",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x767fe9edc9e0df98e07454847909b5e959d7ca0e"),
        venue_asset: "ilv",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x76a0e27618462bdac7a29104bdcfff4e6bfcea2d"),
        venue_asset: "soso",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x77146784315ba81904d654466968e3a7c196d1f3"),
        venue_asset: "tree",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x77777feddddffc19ff86db637967013e6c6a116c"),
        venue_asset: "torn",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x77fba179c79de5b7653f68b5039af940ada60ce0"),
        venue_asset: "forth",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x7a2bc711e19ba6aff6ce8246c546e8c4b4944dfd"),
        venue_asset: "waxe",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x7a58c0be72be218b41c608b7fe7c5bb630736c71"),
        venue_asset: "people",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x7a65cb87f596caf31a4932f074c59c0592be77d7"),
        venue_asset: "zypto",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x7abc8a5768e6be61a6c693a6e4eacb5b60602c4d"),
        venue_asset: "cxt",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x7c5a0ce9267ed19b22f8cae653f198e3e8daf098"),
        venue_asset: "san",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x7cf9a80db3b29ee8efe3710aadb7b95270572d47"),
        venue_asset: "nil",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x7d1afa7b718fb893db30a3abc0cfc608aacfebb0"),
        venue_asset: "matic",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x7d5121505149065b562c789a0145ed750e6e8cdd"),
        venue_asset: "vr",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x7d8146cf21e8d7cbe46054e01588207b51198729"),
        venue_asset: "bob",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x7dd9c5cba05e151c895fde1cf355c9a1d5da6429"),
        venue_asset: "glm",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x7ddc52c4de30e94be3a6a0a2b259b2850f421989"),
        venue_asset: "gomining",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x7f792db54b0e580cdc755178443f0430cf799aca"),
        venue_asset: "volt",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9"),
        venue_asset: "aave",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x808507121b80c02388fad14726482e061b8da827"),
        venue_asset: "pendle",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x812ba41e071c7b7fa4ebcfb62df5f45f6fa853ee"),
        venue_asset: "neiro",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x8143182a775c54578c8b7b3ef77982498866945d"),
        venue_asset: "wquil",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x8207c1ffc5b6804f6024322ccf34f29c3541ae26"),
        venue_asset: "ogn",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x8290333cef9e6d528dd5618fb97a76f268f3edd4"),
        venue_asset: "ankr",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x8292bb45bf1ee4d140127049757c2e0ff06317ed"),
        venue_asset: "rlusd",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x82a605d6d9114f4ad6d5ee461027477eeed31e34"),
        venue_asset: "snsy",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x83e6f1e41cdd28eaceb20cb649155049fac3d5aa"),
        venue_asset: "pols",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x8400d94a5cb0fa0d041a3788e395285d61c9ee5e"),
        venue_asset: "ubt",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x8408d45b61f5823298f19a09b53b7339c0280489"),
        venue_asset: "allo",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x8457ca5040ad67fdebbcc8edce889a335bc0fbfb"),
        venue_asset: "alt",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x84ca8bc7997272c7cfb4d0cd3d55cd942b3c9419"),
        venue_asset: "dia",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x84eaac1b2dc3f84d92ff84c3ec205b1fa74671fc"),
        venue_asset: "camp",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x853d955acef822db058eb8505911ed77f175b99e"),
        venue_asset: "frax",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x868fced65edbf0056c4163515dd840e9f287a4c3"),
        venue_asset: "sign",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x8806926ab68eb5a7b909dcaf6fdbe5d93271d6e2"),
        venue_asset: "uqc",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x888888848b652b3e3a0f34c96e00eec0f3a23f72"),
        venue_asset: "tlm",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x88909d489678dd17aa6d9609f89b0419bf78fd9a"),
        venue_asset: "l3",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x88df592f8eb5d7bd38bfef7deb0fbc02cf3778a0"),
        venue_asset: "trb",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x8a2279d4a90b6fe1c4b30fa660cc9f926797baa2"),
        venue_asset: "chr",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x8a6d4c8735371ebaf8874fbd518b56edd66024eb"),
        venue_asset: "blocks",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x8ab7404063ec4dbcfd4598215992dc3f8ec853d7"),
        venue_asset: "akro",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x8b9b95292f890df47fff5ac9cbe93d5fc242bd51"),
        venue_asset: "befi",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x8d0d000ee44948fc98c9b98a4fa4921476f08b0d"),
        venue_asset: "usd1",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x8de5b80a0c1b02fe4976851d030b36122dbb8624"),
        venue_asset: "vanry",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x8df723295214ea6f21026eeeb4382d475f146f9f"),
        venue_asset: "eurq",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x8e6cd950ad6ba651f6dd608dc70e5886b1aa6b24"),
        venue_asset: "starl",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x8e870d67f660d95d5be530380d0ec0bd388289e1"),
        venue_asset: "usdp",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x8ed97a637a790be1feff5e888d43629dc05408f6"),
        venue_asset: "npc",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x8f693ca8d21b157107184d29d398a8d082b38b76"),
        venue_asset: "data",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x8f8221afbb33998d8584a2b05749ba73c37a938a"),
        venue_asset: "req",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x8fc8f8269ebca376d046ce292dc7eac40c8d358a"),
        venue_asset: "dfi",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x904567252d8f48555b7447c67dca23f0372e16be"),
        venue_asset: "kite",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x908ddb096bfb3acb19e2280aad858186ea4935c4"),
        venue_asset: "ese",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x922d8563631b03c2c4cf817f4d18f6883aba0109"),
        venue_asset: "lock",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x93a2db22b7c736b341c32ff666307f4a9ed910f5"),
        venue_asset: "hyper",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x93ed3fbe21207ec2e8f2d3c3de6e058cb73bc04d"),
        venue_asset: "pnk",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x940a2db1b7008b6c776d4faaca729d6d4a4aa551"),
        venue_asset: "dusk",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x94314a14df63779c99c0764a30e0cd22fa78fc0e"),
        venue_asset: "epic",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x94be6962be41377d5beda8dfe1b100f3bf0eacf3"),
        venue_asset: "dorkl",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x95ad61b0a150d79219dcf64e1e6cc01f0b64c4ce"),
        venue_asset: "shib",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x968f6f898a6df937fc1859b323ac2f14643e3fed"),
        venue_asset: "nwc",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x9813037ee2218799597d83d4a5b6f3b6778218d9"),
        venue_asset: "bone",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x996d67aa9b37df96428ad3608cb21352bf1fdb90"),
        venue_asset: "stzent",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x9aab071b4129b083b01cb5a0cb513ce7eca26fa5"),
        venue_asset: "hunt",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x9b9647431632af44be02ddd22477ed94d14aacaa"),
        venue_asset: "kok",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x9c7beba8f6ef6643abd725e45a4e8387ef260649"),
        venue_asset: "g",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x9d1a7a3191102e9f900faa10540837ba84dcbae7"),
        venue_asset: "euri",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x9d65ff81a3c488d585bbfb0bfe3c7707c7917f54"),
        venue_asset: "ssv",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x9db0fb0aebe6a925b7838d16e3993a3976a64aab"),
        venue_asset: "bam",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x9e32b13ce7f2e80a01932b42553652e053d6ed8e"),
        venue_asset: "metis",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xa0246c9032bc3a600820415ae600c6388619a14d"),
        venue_asset: "farm",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xa02c49da76a085e4e1ee60a6b920ddbc8db599f4"),
        venue_asset: "treat",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xa0b73e1ff0b80914ab6fe0444e65848c4c34450b"),
        venue_asset: "cro",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"),
        venue_asset: "usdc",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xa117000000f279d81a1d3cc75430faa017fa5a2e"),
        venue_asset: "ant",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xa12cc123ba206d4031d1c7f6223d1c2ec249f4f3"),
        venue_asset: "zama",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xa1d0e215a23d7030842fc67ce582a6afa3ccab83"),
        venue_asset: "yfii",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xa2120b9e674d3fc3875f415a7df52e382f141225"),
        venue_asset: "ata",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xa27ec0006e59f245217ff08cd52a7e8b169e62d2"),
        venue_asset: "aztec",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xa2b4c0af19cc16a6cfacce81f192b024d625817d"),
        venue_asset: "kishu",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xa2cd3d43c775978a96bdbf12d733d5a1ed94fb18"),
        venue_asset: "xcn",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xa2e3356610840701bdf5611a53974510ae27e2e1"),
        venue_asset: "wbeth",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xa35923162c49cf95e6bf26623385eb431ad920d3"),
        venue_asset: "turbo",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xa3d4bee77b05d4a0c943877558ce21a763c4fa29"),
        venue_asset: "root",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xa3ee21c306a700e682abcdfe9baa6a08f3820419"),
        venue_asset: "ctc",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xa6c0c097741d55ecd9a3a7def3a8253fd022ceb9"),
        venue_asset: "ava2",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xa71d0588eaf47f12b13cf8ec750430d21df04974"),
        venue_asset: "qom",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xa91ac63d040deb1b7a5e4d4134ad23eb0ba07e14"),
        venue_asset: "bel",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xa9b1eb5908cfc3cdf91f9b8b3a74108598009096"),
        venue_asset: "auction",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xa9e8acf069c58aec8825542845fd754e41a9489a"),
        venue_asset: "pepecoin",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xaa7a9ca87d3694b5755f213b5d04094b8d0f0a6f"),
        venue_asset: "trac",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xaa95f26e30001251fb905d264aa7b00ee9df6c18"),
        venue_asset: "kendu",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xaa9806c938836627ed1a41ae871c7e1889ae02ca"),
        venue_asset: "edgen",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xaaaaaa20d9e0e2461697782ef11675f668207961"),
        venue_asset: "aurora",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xaaaebe6fe48e54f431b0c390cfaf0b017d09d42d"),
        venue_asset: "cel",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xaaee1a9723aadb7afa2810263653a34ba2c21c7a"),
        venue_asset: "mog",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xabd4c63d2616a5201454168269031355f4764337"),
        venue_asset: "order",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xac51066d7bec65dc4589368da368b212745d63e8"),
        venue_asset: "alice",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xad22f63404f7305e4713ccbd4f296f34770513f4"),
        venue_asset: "awc",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xade00c28244d5ce17d72e40330b1c318cd12b7c3"),
        venue_asset: "adx",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xadf7c35560035944e805d98ff17d58cde2449389"),
        venue_asset: "spec",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xae12c5930881c53715b369cec7606b70d8eb229f"),
        venue_asset: "c98",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xae41b275aaaf484b541a5881a2dded9515184cca"),
        venue_asset: "cswap",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xae7ab96520de3a18e5e111b5eaab095312d7fe84"),
        venue_asset: "steth",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xaea46a60368a7bd060eec7df8cba43b7ef41ad85"),
        venue_asset: "fet",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xaf5191b0de278c7286d6c7cc6ab6bb8a73ba2cd6"),
        venue_asset: "stg",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xb0076de78dc50581770bba1d211ddc0ad4f2a241"),
        venue_asset: "edge",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xb056c38f6b7dc4064367403e26424cd2c60655e1"),
        venue_asset: "ceek",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xb0ac2b5a73da0e67a8e5489ba922b3f8d582e058"),
        venue_asset: "shiro",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xb0ffa8000886e57f86dd5264b9582b2ad87b2b91"),
        venue_asset: "w",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xb1110919016846972056ab995054d65560d5f05e"),
        venue_asset: "bill",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xb131f4a55907b10d1f0a50d8ab8fa09ec342cd74"),
        venue_asset: "meme",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xb1f1ee126e9c96231cc3d3fad7c08b4cf873b1f1"),
        venue_asset: "bifi",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xb23d80f5fefcddaa212212f028021b41ded428cf"),
        venue_asset: "prime",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xb2617246d0c6c0087f18703d576831899ca94f01"),
        venue_asset: "zig",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xb3912b20b3abc78c15e85e13ec0bf334fbb924f7"),
        venue_asset: "hana",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xb3999f658c0391d94a37f7ff328f3fec942bcadc"),
        venue_asset: "hft",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xb50721bcf8d664c30412cfbc6cf7a15145234ad1"),
        venue_asset: "arb",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xb528edbef013aff855ac3c50b381f253af13b997"),
        venue_asset: "aevo",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xb612bfc5ce2fb1337bd29f5af24ca85dbb181ce2"),
        venue_asset: "klaus",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xb62132e35a6c13ee1ee0f84dc5d40bad8d815206"),
        venue_asset: "nexo",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xb64ef51c888972c908cfacf59b47c1afbc0ab8ac"),
        venue_asset: "storj",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xb705268213d593b8fd88d3fdeff93aff5cbdcfae"),
        venue_asset: "idex",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xb812837b81a3a6b81d7cd74cfb19a7f2784555e5"),
        venue_asset: "msfton",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xb8baa0e4287890a5f79863ab62b7f175cecbd433"),
        venue_asset: "swrv",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xba100000625a3754423978a60c9317c58a424e3d"),
        venue_asset: "bal",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xba11d00c5f74255f56a5e366f4f77f5a186d7f55"),
        venue_asset: "band",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xba50933c268f567bdc86e1ac131be072c6b0b71a"),
        venue_asset: "arpa",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xba5bde662c17e2adff1075610382b9b691296350"),
        venue_asset: "rare",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xba6b0dbb2ba8daa8f5d6817946393aef8d3a4487"),
        venue_asset: "hsf",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xbb0e17ef65f82ab018d8edd776e8dd940327b28b"),
        venue_asset: "axs",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xbb8774fb97436d23d74c1b882e8e9a69322cfd31"),
        venue_asset: "amznon",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xbba39fd2935d5769116ce38d46a71bde9cf03099"),
        venue_asset: "cho",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xbbbbca6a901c926f240b89eacb641d8aec7aeafd"),
        venue_asset: "lrc",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xbbc2ae13b23d715c30720f079fcd9b4a74093505"),
        venue_asset: "ern",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xbc396689893d065f41bc2c6ecbee5e0085233447"),
        venue_asset: "perp",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xbdbdbdd0c22888e63cb9098ad6d68439197cb091"),
        venue_asset: "bdxn",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xbe0ed4138121ecfc5c0e56b40517da27e6c5226b"),
        venue_asset: "ath",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xbf2179859fc6d5bee9bf9158632dc51678a4100e"),
        venue_asset: "elf",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xbf494f02ee3fde1f20bee6242bce2d1ed0c15e47"),
        venue_asset: "world",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xc00e94cb662c3520282e6f5717214004a7f26888"),
        venue_asset: "comp",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xc011a73ee8576fb46f5e1c5751ca3b9fe0af2a6f"),
        venue_asset: "snx",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"),
        venue_asset: "weth",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xc03fbf20a586fa89c2a5f6f941458e1fbc40c661"),
        venue_asset: "combo",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xc18360217d8f7ab5e7c516566761ea12ce7f9d72"),
        venue_asset: "ens",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xc20059e0317de91738d13af027dfc4a50781b066"),
        venue_asset: "spk",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xc43c6bfeda065fe2c4c11765bf838789bd0bb5de"),
        venue_asset: "red",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xc4441c2be5d8fa8126822b9929ca0b81ea0de38e"),
        venue_asset: "usual",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xc477d038d5420c6a9e0b031712f61c5120090de9"),
        venue_asset: "boson",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xc555d625828c4527d477e595ff1dd5801b4a600e"),
        venue_asset: "mon",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xc581b735a1688071a1746c968e0798d642ede491"),
        venue_asset: "eurt",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xc5f0f7b66764f6ec8c8dff7ba683102295e16409"),
        venue_asset: "fdusd",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xc5fb36dd2fb59d3b98deff88425a3f425ee469ed"),
        venue_asset: "tsuka",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xc669928185dbce49d2230cc9b0979be6dc797957"),
        venue_asset: "bttc",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xc6dddb5bc6e61e0841c54f3e723ae1f3a807260b"),
        venue_asset: "urus",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xc71b5f631354be6853efe9c3ab6b9590f8302e81"),
        venue_asset: "zkj",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xc770eefad204b5180df6a14ee197d99d808ee52d"),
        venue_asset: "fox",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xc83e27f270cce0a3a3a29521173a83f402c1768b"),
        venue_asset: "usdq",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xc944e90c64b2c07662a292be6244bdf05cda44a7"),
        venue_asset: "grt",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xc98d64da73a6616c42117b582e832812e7b8d57f"),
        venue_asset: "rss3",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xc9bca88b04581699fab5aa276ccaff7df957cbbf"),
        venue_asset: "vista",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xca14007eff0db1f8135f4c25b34de49ab0d42766"),
        venue_asset: "strkerc20",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xcb1592591996765ec0efc1f92599a19767ee5ffa"),
        venue_asset: "bio",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xcb21311d3b91b5324f6c11b4f5a656fcacbff122"),
        venue_asset: "qai",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xcbb7c0000ab88b473b1f5afd9ef808440eed33bf"),
        venue_asset: "cbbtc",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xcc8fa225d80b9c7d42f96e9570156c65d6caaa25"),
        venue_asset: "slp",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xccc8cb5229b0ac8069c51fd58367fd1e622afd97"),
        venue_asset: "gods",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xcccccccccc33d538dbc2ee4feab0a7a1ff4e8a94"),
        venue_asset: "cfg",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xcd5fe23c85820f7b72d0926fc9b05b43e359b7ee"),
        venue_asset: "weeth",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xcdf7028ceab81fa0c6971208e83fa7872994bee5"),
        venue_asset: "t",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xcedbea37c8872c4171259cdfd5255cb8923cf8e7"),
        venue_asset: "xan",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xcf0c122c6b73ff809c693db761e7baebe62b6a2e"),
        venue_asset: "floki",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xcf5104d094e3864cfcbda43b82e1cefd26a016eb"),
        venue_asset: "h",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xd0a6053f087e87a25dc60701ba6e663b1a548e85"),
        venue_asset: "lrds",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xd0d56273290d339aaf1417d9bfa1bb8cfe8a0933"),
        venue_asset: "foom",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xd0ec028a3d21533fdd200838f39c85b03679285d"),
        venue_asset: "newt",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xd13c7342e1ef687c5ad21b27c2b65d772cab5c8c"),
        venue_asset: "uos",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xd1d2eb1b1e90b638588728b4130137d262c87cae"),
        venue_asset: "gala",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xd26114cd6ee289accf82350c8d8487fedb8a0c07"),
        venue_asset: "omg",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xd31a59c85ae9d8edefec411d448f90841571b89c"),
        venue_asset: "sol",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xd33526068d116ce69f19a9ee46f0bd304f21a51f"),
        venue_asset: "rpl",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xd47bdf574b4f76210ed503e0efe81b58aa061f3d"),
        venue_asset: "trvl",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xd4f4d0a10bcae123bb6655e8fe93a30d01eebd04"),
        venue_asset: "lnq",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xd533a949740bb3306d119cc777fa900ba034cd52"),
        venue_asset: "crv",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xd9c2d319cd7e6177336b0a9c93c21cb48d84fb54"),
        venue_asset: "hapi",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xd9fcd98c322942075a5c3860693e9f4f03aae07b"),
        venue_asset: "eul",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xda5e1988097297dcdc1f90d4dfe7909e847cbef6"),
        venue_asset: "wlfi",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xdac17f958d2ee523a2206206994597c13d831ec7"),
        venue_asset: "usdt",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xdbb5cf12408a3ac17d668037ce289f9ea75439d7"),
        venue_asset: "wmtx",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xdbb7a34bf10169d6d2d0d02a6cbb436cf4381bfa"),
        venue_asset: "zent",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xdbdb4d16eda451d0503b854cf79d55697f90c8df"),
        venue_asset: "alcx",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xdc035d45d973e3ec169d2276ddab16f1e407384f"),
        venue_asset: "usds",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xddb3422497e61e13543bea06989c0789117555c5"),
        venue_asset: "coti",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xde30da39c46104798bb5aa3fe8b9e0e1f348163f"),
        venue_asset: "gtc",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xde4ee8057785a7e8e800db58f9784845a5c2cbd6"),
        venue_asset: "dexe",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xdef1ca1fb7fbcdc777520aa7f396b4e015f497ab"),
        venue_asset: "cow",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xdefa4e8a7bcba345f687a2f1456f5edd9ce97202"),
        venue_asset: "knc",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xe0b7ad7f8f26e2b00c8b47b5df370f15f90fcf48"),
        venue_asset: "solx",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xe0f63a424a4439cbe457d80e4f4b51ad25b2c56c"),
        venue_asset: "spx",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xe1be424f442d0687129128c6c38aace44f8c8dbc"),
        venue_asset: "zkp",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xe28b3b32b6c345a34ff64674606124dd5aceca30"),
        venue_asset: "inj",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xe2ad0bf751834f2fbdc62a41014f84d67ca1de2a"),
        venue_asset: "era",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xe3c408bd53c31c085a1746af401a4042954ff740"),
        venue_asset: "gmt",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xe41d2489571d322189246dafa5ebde1f4699f498"),
        venue_asset: "zrx",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xe50e009ddb1a4d8ec668eac9d8b2df1f96348707"),
        venue_asset: "ctrl",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xe53ec727dbdeb9e2d5456c3be40cff031ab40a55"),
        venue_asset: "super",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xe66747a101bff2dba3697199dcce5b743b454759"),
        venue_asset: "gt",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xe69ccaaaea33ebfe5b76e0dd373cd9a1a31fd410"),
        venue_asset: "pnut",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xe6bfd33f52d82ccb5b37e16d3dd81f9ffdabb195"),
        venue_asset: "sxt",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xe6fd75ff38adca4b97fbcd938c86b98772431867"),
        venue_asset: "ela",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xe9a95d175a5f4c9369f3b74222402eb1b837693b"),
        venue_asset: "now",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xea26c4ac16d4a5a106820bc8aee85fd0b7b2b664"),
        venue_asset: "qkc",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xec53bf9167f50cdeb3ae105f56099aaab9061f83"),
        venue_asset: "eigen",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xec67005c4e498ec7f55e092bd1d35cbc47c91892"),
        venue_asset: "mln",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xeca82185adce47f39c684352b0439f030f860318"),
        venue_asset: "perl",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xed04915c23f00a313a544955524eb7dbd823143d"),
        venue_asset: "ach",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xee2a03aa6dacf51c18679c516ad5283d8e7c2637"),
        venue_asset: "neiroeth",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xeeaa40b28a2d1b0b08f6f97bb1dd4b75316c6107"),
        venue_asset: "govi",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xeef9f339514298c6a857efcfc1a762af84438dee"),
        venue_asset: "hez",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xef3a930e1ffffacd2fc13434ac81bd278b0ecc8d"),
        venue_asset: "fis",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xf091867ec603a6628ed83d274e835539d82e9cc8"),
        venue_asset: "zeta",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xf0db65d17e30a966c2ae6a21f6bba71cea6e9754"),
        venue_asset: "bard",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xf0f9d895aca5c8678f706fb8216fa22957685a13"),
        venue_asset: "cult",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xf10c41ca085fc8d9326a65408d14dae28a3e69a5"),
        venue_asset: "islm",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xf17e65822b568b3903685a7c9f496cf7656cc6c2"),
        venue_asset: "bico",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xf1f955016ecbcd7321c7266bccfb96c68ea5e49b"),
        venue_asset: "rly",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xf2c88757f8d03634671208935974b60a2a28bdb3"),
        venue_asset: "shell",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xf34960d9d60be18cc1d5afc1a6f012a723a28811"),
        venue_asset: "kcs",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xf3e4872e6a4cf365888d93b6146a2baa7348f1a4"),
        venue_asset: "slvon",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xf4d2888d29d722226fafa5d9b24f9164c092421e"),
        venue_asset: "looks",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xf57d49646621f563b0b905afc8336923ac569ec5"),
        venue_asset: "nex",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xf57e7e7c23978c3caec3c3548e3d615c346e79ff"),
        venue_asset: "imx",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xf6b1117ec07684d3958cad8beb1b302bfd21103f"),
        venue_asset: "tslaon",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xf7168c8abb0ff80116413a8d95396bbdc318a3ff"),
        venue_asset: "keke",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xf816507e690f5aa4e29d164885eb5fa7a5627860"),
        venue_asset: "rato",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xf819d9cb1c2a819fd991781a822de3ca8607c3c9"),
        venue_asset: "unibot",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xf8f173e20e15f3b6cb686fb64724d370689de083"),
        venue_asset: "hei",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xf944e35f95e819e752f3ccb5faf40957d311e8c5"),
        venue_asset: "moca",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xf94e7d0710709388bce3161c32b4eea56d3f91cc"),
        venue_asset: "dsync",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xf970b8e36e23f7fc3fd752eea86f8be8d83375a6"),
        venue_asset: "rcn",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xfa1c09fc8b491b6a4d3ff53a10cad29381b3f949"),
        venue_asset: "ff",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xfa2b947eec368f42195f24f36d2af29f7c24cec2"),
        venue_asset: "usdf",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xfa704148d516b209d52c2d75f239274c8f8eaf1a"),
        venue_asset: "wocta",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xfaba6f8e4a5e8ab82f62fe7c39859fa577269be3"),
        venue_asset: "ondo",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xfad45e47083e4607302aa43c65fb3106f1cd7607"),
        venue_asset: "hoge",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xfc82bb4ba86045af6f327323a46e80412b91b27d"),
        venue_asset: "prom",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xfca59cd816ab1ead66534d82bc21e7515ce441cf"),
        venue_asset: "rari",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xfd418e42783382e86ae91e445406600ba144d162"),
        venue_asset: "zrc",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xfdffb411c4a70aa7c95d5c981a6fb4da867e1111"),
        venue_asset: "sahara",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xfe0c30065b384f05761f15d0cc899d4f9f9cc0eb"),
        venue_asset: "ethfi",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xfe3e6a25e6b192a42a44ecddcd13796471735acf"),
        venue_asset: "reef",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xfe67a4450907459c3e1fff623aa927dd4e28c67a"),
        venue_asset: "next",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xfedc5f4a6c38211c1338aa411018dfaf26612c08"),
        venue_asset: "spyon",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xff20817765cb7f73d4bde2e66e067e58d11095c2"),
        venue_asset: "amp",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xff56cc6b1e6ded347aa0b7676c85ab0b3d08b0fa"),
        venue_asset: "orbs",
    },
];

const CHANGENOW_EVM_42161_ASSETS: &[VenueAssetEntry] = &[
    VenueAssetEntry {
        router_asset: RouterAssetKind::Native,
        venue_asset: "eth",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x09e18590e8f76b6cf471b3cd75fe1a1a9d2b2c2b"),
        venue_asset: "aidoge",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x0c1c1c109fe34733fca54b82d7b46b75cfb71f6e"),
        venue_asset: "chip",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x0c880f6761f1af8d9aa9c466984b80dab9a8c9e8"),
        venue_asset: "pendle",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x11cdb42b0eb46d95f990bedd4695a6e3fa034978"),
        venue_asset: "crv",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x13ad51ed4f1b7e9dc168d8a00cb3f4ddd85efa60"),
        venue_asset: "ldo",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x18c11fd286c5ec11c3b683caa813b77f5163a122"),
        venue_asset: "gns",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x1cd9a56c8c2ea913c70319a44da75e99255aa46f"),
        venue_asset: "obt",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f"),
        venue_asset: "wbtc",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x37a645648df29205c6261289983fb04ecd70b4b3"),
        venue_asset: "anime",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x4cb9a7ae498cedcbb5eae9f25736ae7d428c9d66"),
        venue_asset: "xai",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x539bde0d7dbd336b79148aa742883198bbf60342"),
        venue_asset: "magic",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x6985884c4392d348587b19cb9eaaf157f13271cd"),
        venue_asset: "zro",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x7189fb5b6504bbff6a852b13b7b82a3c118fdc27"),
        venue_asset: "ethfi",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x912ce59144191c1204e64559fe8253a0e49e6548"),
        venue_asset: "arb",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x9623063377ad1b27544c965ccd7342f7ea7e88c7"),
        venue_asset: "grt",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xaf88d065e77c8cc2239327c5edb3a432268e5831"),
        venue_asset: "usdc",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xcafcd85d8ca7ad1e1c6f82f651fa15e33aefd07b"),
        venue_asset: "woo",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xda10009cbd5d07dd0cecc66161fc93d7c9000da1"),
        venue_asset: "dai",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xf97f4df75117a78c1a5a0dbb814af92458539fb4"),
        venue_asset: "link",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xfa7f8980b0f1e64a2062791cc3b0871572f1f7f0"),
        venue_asset: "uni",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xfc5a1a6eb076a2c7ad06ed22c90d7e710e35ad0a"),
        venue_asset: "gmx",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xfd086bc7cd5c481dcc9c85ebe478a1c0b69fcbb9"),
        venue_asset: "usdt",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xff970a61a04b1ca14834a43f5de4533ebddb5cc8"),
        venue_asset: "arbusdce",
    },
];

const CHANGENOW_EVM_8453_ASSETS: &[VenueAssetEntry] = &[
    VenueAssetEntry {
        router_asset: RouterAssetKind::Native,
        venue_asset: "eth",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x00000000a22c618fd6b4d7e9a335c4b96b189a38"),
        venue_asset: "towns",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x01aac2b594f7bdbec740f0f1aa22910ebb4b74ab"),
        venue_asset: "unio",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x0b3e328455c4059eeb9e3f84b5543f74e24e7e1b"),
        venue_asset: "virtual",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x0c1dc73159e30c4b06170f2593d3118968a0dca5"),
        venue_asset: "gps",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x1111111111166b7fe7bd91427724b487980afc69"),
        venue_asset: "zora",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x16ee7ecac70d1028e7712751e2ee6ba808a7dd92"),
        venue_asset: "fun",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x1b4617734c43f6159f3a70b7e06d883647512778"),
        venue_asset: "awe",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x1bc0c42215582d5a085795f4badbac3ff36d1bcb"),
        venue_asset: "clanker",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x1f16e03c1a5908818f47f6ee7bb16690b40d0671"),
        venue_asset: "recall",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x24fcfc492c1393274b6bcd568ac9e225bec93584"),
        venue_asset: "mavia",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x2c24497d4086490e7ead87cc12597fb50c2e6ed6"),
        venue_asset: "f",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x2da56acb9ea78330f947bd57c54119debda7af71"),
        venue_asset: "mog",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x30c7235866872213f68cb1f08c37cb9eccb93452"),
        venue_asset: "prompt",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x4bfaa776991e85e5f8b1255461cbbd216cfc714f"),
        venue_asset: "home",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x4ed4e862860bed51a9570b96d89af5e1b0efefed"),
        venue_asset: "degen",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x4f9fd6be4a90f2620860d680c0d4d5fb53d1a825"),
        venue_asset: "aixbt",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x532f27101965dd16442e59d40670faf5ebb142e4"),
        venue_asset: "brett",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x59264f02d301281f3393e1385c0aefd446eb0f00"),
        venue_asset: "parti",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x5ab3d4c385b400f3abb49e80de2faf6a88a7b691"),
        venue_asset: "flock",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x624e2e7fdc8903165f64891672267ab0fcb98831"),
        venue_asset: "soso",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x696f9436b67233384889472cd7cd58a6fb5df4f1"),
        venue_asset: "avnt",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x6985884c4392d348587b19cb9eaaf157f13271cd"),
        venue_asset: "zro",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x768be13e1680b5ebe0024c42c896e3db59ec0149"),
        venue_asset: "ski",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x7aafd31a321d3627b30a8e2171264b56852187fe"),
        venue_asset: "mira",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x833589fcd6edb6e08f4c7c32d4f71b54bda02913"),
        venue_asset: "usdc",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x868fced65edbf0056c4163515dd840e9f287a4c3"),
        venue_asset: "sign",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x9126236476efba9ad8ab77855c60eb5bf37586eb"),
        venue_asset: "check",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x940181a94a35a4569e4529a3cdfb74e38fd98631"),
        venue_asset: "aero",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x98d0baa52b2d063e780de12f615f963fe8537553"),
        venue_asset: "kaito",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0x9c632e6aaa3ea73f91554f8a3cb2ed2f29605e0c"),
        venue_asset: "xcn",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xa749de6c28262b7ffbc5de27dc845dd7ecd2b358"),
        venue_asset: "vfy",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xac1bd2486aaf3b5c0fc3fd868558b082a531b2b4"),
        venue_asset: "toshi",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xacfe6019ed1a7dc6f7b508c02d1b04ec88cc21bf"),
        venue_asset: "vvv",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xb3b32f9f8827d4634fe7d973fa1034ec9fddb3b3"),
        venue_asset: "b3",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xba12bc7b210e61e5d3110b997a63ea216e0e18f7"),
        venue_asset: "c",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xc0041ef357b183448b235a8ea73ce4e4ec8c265f"),
        venue_asset: "cookie",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xc0634090f2fe6c6d75e61be2b949464abb498973"),
        venue_asset: "kta",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xc08cd26474722ce93f4d0c34d16201461c10aa8c"),
        venue_asset: "carv",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xc729777d0470f30612b1564fd96e8dd26f5814e3"),
        venue_asset: "sapien",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xd722e55c1d9d9fa0021a5215cbb904b92b3dc5d4"),
        venue_asset: "rdnt",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xe0cd4cacddcbf4f36e845407ce53e87717b6601d"),
        venue_asset: "icnt",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xe2b1dc2d4a3b4e59fdf0c47b71a7a86391a8b35a"),
        venue_asset: "rwa",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xf43eb8de897fbc7f2502483b2bef7bb9ea179229"),
        venue_asset: "zen",
    },
    VenueAssetEntry {
        router_asset: RouterAssetKind::Reference("0xfb42da273158b0f642f59f2ba7cc1d5457481677"),
        venue_asset: "lingo",
    },
];

const CHANGENOW_CHAINS: &[VenueChainAssetsSpec] = &[
    VenueChainAssetsSpec {
        router_chain: "bitcoin",
        venue_chain: "btc",
        asset_policy: VenueAssetPolicy::ListedOnly,
        assets: CHANGENOW_BITCOIN_ASSETS,
    },
    VenueChainAssetsSpec {
        router_chain: "evm:1",
        venue_chain: "eth",
        asset_policy: VenueAssetPolicy::ListedOnly,
        assets: CHANGENOW_EVM_1_ASSETS,
    },
    VenueChainAssetsSpec {
        router_chain: "evm:42161",
        venue_chain: "arbitrum",
        asset_policy: VenueAssetPolicy::ListedOnly,
        assets: CHANGENOW_EVM_42161_ASSETS,
    },
    VenueChainAssetsSpec {
        router_chain: "evm:8453",
        venue_chain: "base",
        asset_policy: VenueAssetPolicy::ListedOnly,
        assets: CHANGENOW_EVM_8453_ASSETS,
    },
];

pub const CHANGENOW_ASSET_MAP_SPEC: VenueAssetMapSpec = VenueAssetMapSpec {
    provider: ProviderId::Changenow,
    chains: CHANGENOW_CHAINS,
};
